const POKER_CARDS_DATA = [
  {
    "id": 1,
    "code": "ace_spades",
    "name": "Át (Ace) Bích ♠",
    "shortName": "A♠",
    "rank": "Át (Ace)",
    "suit": "Bích",
    "symbol": "♠",
    "color": "Màu đen",
    "image": "Porker/ace_of_spades.png",
    "description": "Quân bài Át (Ace) thuộc chất Bích (♠) trong bộ bài tây chuẩn 52 lá.",
    "advice": "Mang biểu trưng của chất Bích (♠) và bậc số Át (Ace)."
  },
  {
    "id": 2,
    "code": "2_spades",
    "name": "Hai (2) Bích ♠",
    "shortName": "2♠",
    "rank": "Hai (2)",
    "suit": "Bích",
    "symbol": "♠",
    "color": "Màu đen",
    "image": "Porker/2_of_spades.png",
    "description": "Quân bài Hai (2) thuộc chất Bích (♠) trong bộ bài tây chuẩn 52 lá.",
    "advice": "Mang biểu trưng của chất Bích (♠) và bậc số Hai (2)."
  },
  {
    "id": 3,
    "code": "3_spades",
    "name": "Ba (3) Bích ♠",
    "shortName": "3♠",
    "rank": "Ba (3)",
    "suit": "Bích",
    "symbol": "♠",
    "color": "Màu đen",
    "image": "Porker/3_of_spades.png",
    "description": "Quân bài Ba (3) thuộc chất Bích (♠) trong bộ bài tây chuẩn 52 lá.",
    "advice": "Mang biểu trưng của chất Bích (♠) và bậc số Ba (3)."
  },
  {
    "id": 4,
    "code": "4_spades",
    "name": "Bốn (4) Bích ♠",
    "shortName": "4♠",
    "rank": "Bốn (4)",
    "suit": "Bích",
    "symbol": "♠",
    "color": "Màu đen",
    "image": "Porker/4_of_spades.png",
    "description": "Quân bài Bốn (4) thuộc chất Bích (♠) trong bộ bài tây chuẩn 52 lá.",
    "advice": "Mang biểu trưng của chất Bích (♠) và bậc số Bốn (4)."
  },
  {
    "id": 5,
    "code": "5_spades",
    "name": "Năm (5) Bích ♠",
    "shortName": "5♠",
    "rank": "Năm (5)",
    "suit": "Bích",
    "symbol": "♠",
    "color": "Màu đen",
    "image": "Porker/5_of_spades.png",
    "description": "Quân bài Năm (5) thuộc chất Bích (♠) trong bộ bài tây chuẩn 52 lá.",
    "advice": "Mang biểu trưng của chất Bích (♠) và bậc số Năm (5)."
  },
  {
    "id": 6,
    "code": "6_spades",
    "name": "Sáu (6) Bích ♠",
    "shortName": "6♠",
    "rank": "Sáu (6)",
    "suit": "Bích",
    "symbol": "♠",
    "color": "Màu đen",
    "image": "Porker/6_of_spades.png",
    "description": "Quân bài Sáu (6) thuộc chất Bích (♠) trong bộ bài tây chuẩn 52 lá.",
    "advice": "Mang biểu trưng của chất Bích (♠) và bậc số Sáu (6)."
  },
  {
    "id": 7,
    "code": "7_spades",
    "name": "Bảy (7) Bích ♠",
    "shortName": "7♠",
    "rank": "Bảy (7)",
    "suit": "Bích",
    "symbol": "♠",
    "color": "Màu đen",
    "image": "Porker/7_of_spades.png",
    "description": "Quân bài Bảy (7) thuộc chất Bích (♠) trong bộ bài tây chuẩn 52 lá.",
    "advice": "Mang biểu trưng của chất Bích (♠) và bậc số Bảy (7)."
  },
  {
    "id": 8,
    "code": "8_spades",
    "name": "Tám (8) Bích ♠",
    "shortName": "8♠",
    "rank": "Tám (8)",
    "suit": "Bích",
    "symbol": "♠",
    "color": "Màu đen",
    "image": "Porker/8_of_spades.png",
    "description": "Quân bài Tám (8) thuộc chất Bích (♠) trong bộ bài tây chuẩn 52 lá.",
    "advice": "Mang biểu trưng của chất Bích (♠) và bậc số Tám (8)."
  },
  {
    "id": 9,
    "code": "9_spades",
    "name": "Chín (9) Bích ♠",
    "shortName": "9♠",
    "rank": "Chín (9)",
    "suit": "Bích",
    "symbol": "♠",
    "color": "Màu đen",
    "image": "Porker/9_of_spades.png",
    "description": "Quân bài Chín (9) thuộc chất Bích (♠) trong bộ bài tây chuẩn 52 lá.",
    "advice": "Mang biểu trưng của chất Bích (♠) và bậc số Chín (9)."
  },
  {
    "id": 10,
    "code": "10_spades",
    "name": "Mười (10) Bích ♠",
    "shortName": "10♠",
    "rank": "Mười (10)",
    "suit": "Bích",
    "symbol": "♠",
    "color": "Màu đen",
    "image": "Porker/10_of_spades.png",
    "description": "Quân bài Mười (10) thuộc chất Bích (♠) trong bộ bài tây chuẩn 52 lá.",
    "advice": "Mang biểu trưng của chất Bích (♠) và bậc số Mười (10)."
  },
  {
    "id": 11,
    "code": "jack_spades",
    "name": "J (Jack / Bồi) Bích ♠",
    "shortName": "J♠",
    "rank": "J (Jack / Bồi)",
    "suit": "Bích",
    "symbol": "♠",
    "color": "Màu đen",
    "image": "Porker/jack_of_spades.png",
    "description": "Quân bài J (Jack / Bồi) thuộc chất Bích (♠) trong bộ bài tây chuẩn 52 lá.",
    "advice": "Mang biểu trưng của chất Bích (♠) và bậc số J (Jack / Bồi)."
  },
  {
    "id": 12,
    "code": "queen_spades",
    "name": "Q (Queen / Đầm) Bích ♠",
    "shortName": "Q♠",
    "rank": "Q (Queen / Đầm)",
    "suit": "Bích",
    "symbol": "♠",
    "color": "Màu đen",
    "image": "Porker/queen_of_spades.png",
    "description": "Quân bài Q (Queen / Đầm) thuộc chất Bích (♠) trong bộ bài tây chuẩn 52 lá.",
    "advice": "Mang biểu trưng của chất Bích (♠) và bậc số Q (Queen / Đầm)."
  },
  {
    "id": 13,
    "code": "king_spades",
    "name": "K (King / Già) Bích ♠",
    "shortName": "K♠",
    "rank": "K (King / Già)",
    "suit": "Bích",
    "symbol": "♠",
    "color": "Màu đen",
    "image": "Porker/king_of_spades.png",
    "description": "Quân bài K (King / Già) thuộc chất Bích (♠) trong bộ bài tây chuẩn 52 lá.",
    "advice": "Mang biểu trưng của chất Bích (♠) và bậc số K (King / Già)."
  },
  {
    "id": 14,
    "code": "ace_hearts",
    "name": "Át (Ace) Cơ ♥",
    "shortName": "A♥",
    "rank": "Át (Ace)",
    "suit": "Cơ",
    "symbol": "♥",
    "color": "Màu đỏ",
    "image": "Porker/ace_of_hearts.png",
    "description": "Quân bài Át (Ace) thuộc chất Cơ (♥) trong bộ bài tây chuẩn 52 lá.",
    "advice": "Mang biểu trưng của chất Cơ (♥) và bậc số Át (Ace)."
  },
  {
    "id": 15,
    "code": "2_hearts",
    "name": "Hai (2) Cơ ♥",
    "shortName": "2♥",
    "rank": "Hai (2)",
    "suit": "Cơ",
    "symbol": "♥",
    "color": "Màu đỏ",
    "image": "Porker/2_of_hearts.png",
    "description": "Quân bài Hai (2) thuộc chất Cơ (♥) trong bộ bài tây chuẩn 52 lá.",
    "advice": "Mang biểu trưng của chất Cơ (♥) và bậc số Hai (2)."
  },
  {
    "id": 16,
    "code": "3_hearts",
    "name": "Ba (3) Cơ ♥",
    "shortName": "3♥",
    "rank": "Ba (3)",
    "suit": "Cơ",
    "symbol": "♥",
    "color": "Màu đỏ",
    "image": "Porker/3_of_hearts.png",
    "description": "Quân bài Ba (3) thuộc chất Cơ (♥) trong bộ bài tây chuẩn 52 lá.",
    "advice": "Mang biểu trưng của chất Cơ (♥) và bậc số Ba (3)."
  },
  {
    "id": 17,
    "code": "4_hearts",
    "name": "Bốn (4) Cơ ♥",
    "shortName": "4♥",
    "rank": "Bốn (4)",
    "suit": "Cơ",
    "symbol": "♥",
    "color": "Màu đỏ",
    "image": "Porker/4_of_hearts.png",
    "description": "Quân bài Bốn (4) thuộc chất Cơ (♥) trong bộ bài tây chuẩn 52 lá.",
    "advice": "Mang biểu trưng của chất Cơ (♥) và bậc số Bốn (4)."
  },
  {
    "id": 18,
    "code": "5_hearts",
    "name": "Năm (5) Cơ ♥",
    "shortName": "5♥",
    "rank": "Năm (5)",
    "suit": "Cơ",
    "symbol": "♥",
    "color": "Màu đỏ",
    "image": "Porker/5_of_hearts.png",
    "description": "Quân bài Năm (5) thuộc chất Cơ (♥) trong bộ bài tây chuẩn 52 lá.",
    "advice": "Mang biểu trưng của chất Cơ (♥) và bậc số Năm (5)."
  },
  {
    "id": 19,
    "code": "6_hearts",
    "name": "Sáu (6) Cơ ♥",
    "shortName": "6♥",
    "rank": "Sáu (6)",
    "suit": "Cơ",
    "symbol": "♥",
    "color": "Màu đỏ",
    "image": "Porker/6_of_hearts.png",
    "description": "Quân bài Sáu (6) thuộc chất Cơ (♥) trong bộ bài tây chuẩn 52 lá.",
    "advice": "Mang biểu trưng của chất Cơ (♥) và bậc số Sáu (6)."
  },
  {
    "id": 20,
    "code": "7_hearts",
    "name": "Bảy (7) Cơ ♥",
    "shortName": "7♥",
    "rank": "Bảy (7)",
    "suit": "Cơ",
    "symbol": "♥",
    "color": "Màu đỏ",
    "image": "Porker/7_of_hearts.png",
    "description": "Quân bài Bảy (7) thuộc chất Cơ (♥) trong bộ bài tây chuẩn 52 lá.",
    "advice": "Mang biểu trưng của chất Cơ (♥) và bậc số Bảy (7)."
  },
  {
    "id": 21,
    "code": "8_hearts",
    "name": "Tám (8) Cơ ♥",
    "shortName": "8♥",
    "rank": "Tám (8)",
    "suit": "Cơ",
    "symbol": "♥",
    "color": "Màu đỏ",
    "image": "Porker/8_of_hearts.png",
    "description": "Quân bài Tám (8) thuộc chất Cơ (♥) trong bộ bài tây chuẩn 52 lá.",
    "advice": "Mang biểu trưng của chất Cơ (♥) và bậc số Tám (8)."
  },
  {
    "id": 22,
    "code": "9_hearts",
    "name": "Chín (9) Cơ ♥",
    "shortName": "9♥",
    "rank": "Chín (9)",
    "suit": "Cơ",
    "symbol": "♥",
    "color": "Màu đỏ",
    "image": "Porker/9_of_hearts.png",
    "description": "Quân bài Chín (9) thuộc chất Cơ (♥) trong bộ bài tây chuẩn 52 lá.",
    "advice": "Mang biểu trưng của chất Cơ (♥) và bậc số Chín (9)."
  },
  {
    "id": 23,
    "code": "10_hearts",
    "name": "Mười (10) Cơ ♥",
    "shortName": "10♥",
    "rank": "Mười (10)",
    "suit": "Cơ",
    "symbol": "♥",
    "color": "Màu đỏ",
    "image": "Porker/10_of_hearts.png",
    "description": "Quân bài Mười (10) thuộc chất Cơ (♥) trong bộ bài tây chuẩn 52 lá.",
    "advice": "Mang biểu trưng của chất Cơ (♥) và bậc số Mười (10)."
  },
  {
    "id": 24,
    "code": "jack_hearts",
    "name": "J (Jack / Bồi) Cơ ♥",
    "shortName": "J♥",
    "rank": "J (Jack / Bồi)",
    "suit": "Cơ",
    "symbol": "♥",
    "color": "Màu đỏ",
    "image": "Porker/jack_of_hearts.png",
    "description": "Quân bài J (Jack / Bồi) thuộc chất Cơ (♥) trong bộ bài tây chuẩn 52 lá.",
    "advice": "Mang biểu trưng của chất Cơ (♥) và bậc số J (Jack / Bồi)."
  },
  {
    "id": 25,
    "code": "queen_hearts",
    "name": "Q (Queen / Đầm) Cơ ♥",
    "shortName": "Q♥",
    "rank": "Q (Queen / Đầm)",
    "suit": "Cơ",
    "symbol": "♥",
    "color": "Màu đỏ",
    "image": "Porker/queen_of_hearts.png",
    "description": "Quân bài Q (Queen / Đầm) thuộc chất Cơ (♥) trong bộ bài tây chuẩn 52 lá.",
    "advice": "Mang biểu trưng của chất Cơ (♥) và bậc số Q (Queen / Đầm)."
  },
  {
    "id": 26,
    "code": "king_hearts",
    "name": "K (King / Già) Cơ ♥",
    "shortName": "K♥",
    "rank": "K (King / Già)",
    "suit": "Cơ",
    "symbol": "♥",
    "color": "Màu đỏ",
    "image": "Porker/king_of_hearts.png",
    "description": "Quân bài K (King / Già) thuộc chất Cơ (♥) trong bộ bài tây chuẩn 52 lá.",
    "advice": "Mang biểu trưng của chất Cơ (♥) và bậc số K (King / Già)."
  },
  {
    "id": 27,
    "code": "ace_diamonds",
    "name": "Át (Ace) Rô ♦",
    "shortName": "A♦",
    "rank": "Át (Ace)",
    "suit": "Rô",
    "symbol": "♦",
    "color": "Màu đỏ",
    "image": "Porker/ace_of_diamonds.png",
    "description": "Quân bài Át (Ace) thuộc chất Rô (♦) trong bộ bài tây chuẩn 52 lá.",
    "advice": "Mang biểu trưng của chất Rô (♦) và bậc số Át (Ace)."
  },
  {
    "id": 28,
    "code": "2_diamonds",
    "name": "Hai (2) Rô ♦",
    "shortName": "2♦",
    "rank": "Hai (2)",
    "suit": "Rô",
    "symbol": "♦",
    "color": "Màu đỏ",
    "image": "Porker/2_of_diamonds.png",
    "description": "Quân bài Hai (2) thuộc chất Rô (♦) trong bộ bài tây chuẩn 52 lá.",
    "advice": "Mang biểu trưng của chất Rô (♦) và bậc số Hai (2)."
  },
  {
    "id": 29,
    "code": "3_diamonds",
    "name": "Ba (3) Rô ♦",
    "shortName": "3♦",
    "rank": "Ba (3)",
    "suit": "Rô",
    "symbol": "♦",
    "color": "Màu đỏ",
    "image": "Porker/3_of_diamonds.png",
    "description": "Quân bài Ba (3) thuộc chất Rô (♦) trong bộ bài tây chuẩn 52 lá.",
    "advice": "Mang biểu trưng của chất Rô (♦) và bậc số Ba (3)."
  },
  {
    "id": 30,
    "code": "4_diamonds",
    "name": "Bốn (4) Rô ♦",
    "shortName": "4♦",
    "rank": "Bốn (4)",
    "suit": "Rô",
    "symbol": "♦",
    "color": "Màu đỏ",
    "image": "Porker/4_of_diamonds.png",
    "description": "Quân bài Bốn (4) thuộc chất Rô (♦) trong bộ bài tây chuẩn 52 lá.",
    "advice": "Mang biểu trưng của chất Rô (♦) và bậc số Bốn (4)."
  },
  {
    "id": 31,
    "code": "5_diamonds",
    "name": "Năm (5) Rô ♦",
    "shortName": "5♦",
    "rank": "Năm (5)",
    "suit": "Rô",
    "symbol": "♦",
    "color": "Màu đỏ",
    "image": "Porker/5_of_diamonds.png",
    "description": "Quân bài Năm (5) thuộc chất Rô (♦) trong bộ bài tây chuẩn 52 lá.",
    "advice": "Mang biểu trưng của chất Rô (♦) và bậc số Năm (5)."
  },
  {
    "id": 32,
    "code": "6_diamonds",
    "name": "Sáu (6) Rô ♦",
    "shortName": "6♦",
    "rank": "Sáu (6)",
    "suit": "Rô",
    "symbol": "♦",
    "color": "Màu đỏ",
    "image": "Porker/6_of_diamonds.png",
    "description": "Quân bài Sáu (6) thuộc chất Rô (♦) trong bộ bài tây chuẩn 52 lá.",
    "advice": "Mang biểu trưng của chất Rô (♦) và bậc số Sáu (6)."
  },
  {
    "id": 33,
    "code": "7_diamonds",
    "name": "Bảy (7) Rô ♦",
    "shortName": "7♦",
    "rank": "Bảy (7)",
    "suit": "Rô",
    "symbol": "♦",
    "color": "Màu đỏ",
    "image": "Porker/7_of_diamonds.png",
    "description": "Quân bài Bảy (7) thuộc chất Rô (♦) trong bộ bài tây chuẩn 52 lá.",
    "advice": "Mang biểu trưng của chất Rô (♦) và bậc số Bảy (7)."
  },
  {
    "id": 34,
    "code": "8_diamonds",
    "name": "Tám (8) Rô ♦",
    "shortName": "8♦",
    "rank": "Tám (8)",
    "suit": "Rô",
    "symbol": "♦",
    "color": "Màu đỏ",
    "image": "Porker/8_of_diamonds.png",
    "description": "Quân bài Tám (8) thuộc chất Rô (♦) trong bộ bài tây chuẩn 52 lá.",
    "advice": "Mang biểu trưng của chất Rô (♦) và bậc số Tám (8)."
  },
  {
    "id": 35,
    "code": "9_diamonds",
    "name": "Chín (9) Rô ♦",
    "shortName": "9♦",
    "rank": "Chín (9)",
    "suit": "Rô",
    "symbol": "♦",
    "color": "Màu đỏ",
    "image": "Porker/9_of_diamonds.png",
    "description": "Quân bài Chín (9) thuộc chất Rô (♦) trong bộ bài tây chuẩn 52 lá.",
    "advice": "Mang biểu trưng của chất Rô (♦) và bậc số Chín (9)."
  },
  {
    "id": 36,
    "code": "10_diamonds",
    "name": "Mười (10) Rô ♦",
    "shortName": "10♦",
    "rank": "Mười (10)",
    "suit": "Rô",
    "symbol": "♦",
    "color": "Màu đỏ",
    "image": "Porker/10_of_diamonds.png",
    "description": "Quân bài Mười (10) thuộc chất Rô (♦) trong bộ bài tây chuẩn 52 lá.",
    "advice": "Mang biểu trưng của chất Rô (♦) và bậc số Mười (10)."
  },
  {
    "id": 37,
    "code": "jack_diamonds",
    "name": "J (Jack / Bồi) Rô ♦",
    "shortName": "J♦",
    "rank": "J (Jack / Bồi)",
    "suit": "Rô",
    "symbol": "♦",
    "color": "Màu đỏ",
    "image": "Porker/jack_of_diamonds.png",
    "description": "Quân bài J (Jack / Bồi) thuộc chất Rô (♦) trong bộ bài tây chuẩn 52 lá.",
    "advice": "Mang biểu trưng của chất Rô (♦) và bậc số J (Jack / Bồi)."
  },
  {
    "id": 38,
    "code": "queen_diamonds",
    "name": "Q (Queen / Đầm) Rô ♦",
    "shortName": "Q♦",
    "rank": "Q (Queen / Đầm)",
    "suit": "Rô",
    "symbol": "♦",
    "color": "Màu đỏ",
    "image": "Porker/queen_of_diamonds.png",
    "description": "Quân bài Q (Queen / Đầm) thuộc chất Rô (♦) trong bộ bài tây chuẩn 52 lá.",
    "advice": "Mang biểu trưng của chất Rô (♦) và bậc số Q (Queen / Đầm)."
  },
  {
    "id": 39,
    "code": "king_diamonds",
    "name": "K (King / Già) Rô ♦",
    "shortName": "K♦",
    "rank": "K (King / Già)",
    "suit": "Rô",
    "symbol": "♦",
    "color": "Màu đỏ",
    "image": "Porker/king_of_diamonds.png",
    "description": "Quân bài K (King / Già) thuộc chất Rô (♦) trong bộ bài tây chuẩn 52 lá.",
    "advice": "Mang biểu trưng của chất Rô (♦) và bậc số K (King / Già)."
  },
  {
    "id": 40,
    "code": "ace_clubs",
    "name": "Át (Ace) Tép (Chuồn) ♣",
    "shortName": "A♣",
    "rank": "Át (Ace)",
    "suit": "Tép (Chuồn)",
    "symbol": "♣",
    "color": "Màu đen",
    "image": "Porker/ace_of_clubs.png",
    "description": "Quân bài Át (Ace) thuộc chất Tép (Chuồn) (♣) trong bộ bài tây chuẩn 52 lá.",
    "advice": "Mang biểu trưng của chất Tép (Chuồn) (♣) và bậc số Át (Ace)."
  },
  {
    "id": 41,
    "code": "2_clubs",
    "name": "Hai (2) Tép (Chuồn) ♣",
    "shortName": "2♣",
    "rank": "Hai (2)",
    "suit": "Tép (Chuồn)",
    "symbol": "♣",
    "color": "Màu đen",
    "image": "Porker/2_of_clubs.png",
    "description": "Quân bài Hai (2) thuộc chất Tép (Chuồn) (♣) trong bộ bài tây chuẩn 52 lá.",
    "advice": "Mang biểu trưng của chất Tép (Chuồn) (♣) và bậc số Hai (2)."
  },
  {
    "id": 42,
    "code": "3_clubs",
    "name": "Ba (3) Tép (Chuồn) ♣",
    "shortName": "3♣",
    "rank": "Ba (3)",
    "suit": "Tép (Chuồn)",
    "symbol": "♣",
    "color": "Màu đen",
    "image": "Porker/3_of_clubs.png",
    "description": "Quân bài Ba (3) thuộc chất Tép (Chuồn) (♣) trong bộ bài tây chuẩn 52 lá.",
    "advice": "Mang biểu trưng của chất Tép (Chuồn) (♣) và bậc số Ba (3)."
  },
  {
    "id": 43,
    "code": "4_clubs",
    "name": "Bốn (4) Tép (Chuồn) ♣",
    "shortName": "4♣",
    "rank": "Bốn (4)",
    "suit": "Tép (Chuồn)",
    "symbol": "♣",
    "color": "Màu đen",
    "image": "Porker/4_of_clubs.png",
    "description": "Quân bài Bốn (4) thuộc chất Tép (Chuồn) (♣) trong bộ bài tây chuẩn 52 lá.",
    "advice": "Mang biểu trưng của chất Tép (Chuồn) (♣) và bậc số Bốn (4)."
  },
  {
    "id": 44,
    "code": "5_clubs",
    "name": "Năm (5) Tép (Chuồn) ♣",
    "shortName": "5♣",
    "rank": "Năm (5)",
    "suit": "Tép (Chuồn)",
    "symbol": "♣",
    "color": "Màu đen",
    "image": "Porker/5_of_clubs.png",
    "description": "Quân bài Năm (5) thuộc chất Tép (Chuồn) (♣) trong bộ bài tây chuẩn 52 lá.",
    "advice": "Mang biểu trưng của chất Tép (Chuồn) (♣) và bậc số Năm (5)."
  },
  {
    "id": 45,
    "code": "6_clubs",
    "name": "Sáu (6) Tép (Chuồn) ♣",
    "shortName": "6♣",
    "rank": "Sáu (6)",
    "suit": "Tép (Chuồn)",
    "symbol": "♣",
    "color": "Màu đen",
    "image": "Porker/6_of_clubs.png",
    "description": "Quân bài Sáu (6) thuộc chất Tép (Chuồn) (♣) trong bộ bài tây chuẩn 52 lá.",
    "advice": "Mang biểu trưng của chất Tép (Chuồn) (♣) và bậc số Sáu (6)."
  },
  {
    "id": 46,
    "code": "7_clubs",
    "name": "Bảy (7) Tép (Chuồn) ♣",
    "shortName": "7♣",
    "rank": "Bảy (7)",
    "suit": "Tép (Chuồn)",
    "symbol": "♣",
    "color": "Màu đen",
    "image": "Porker/7_of_clubs.png",
    "description": "Quân bài Bảy (7) thuộc chất Tép (Chuồn) (♣) trong bộ bài tây chuẩn 52 lá.",
    "advice": "Mang biểu trưng của chất Tép (Chuồn) (♣) và bậc số Bảy (7)."
  },
  {
    "id": 47,
    "code": "8_clubs",
    "name": "Tám (8) Tép (Chuồn) ♣",
    "shortName": "8♣",
    "rank": "Tám (8)",
    "suit": "Tép (Chuồn)",
    "symbol": "♣",
    "color": "Màu đen",
    "image": "Porker/8_of_clubs.png",
    "description": "Quân bài Tám (8) thuộc chất Tép (Chuồn) (♣) trong bộ bài tây chuẩn 52 lá.",
    "advice": "Mang biểu trưng của chất Tép (Chuồn) (♣) và bậc số Tám (8)."
  },
  {
    "id": 48,
    "code": "9_clubs",
    "name": "Chín (9) Tép (Chuồn) ♣",
    "shortName": "9♣",
    "rank": "Chín (9)",
    "suit": "Tép (Chuồn)",
    "symbol": "♣",
    "color": "Màu đen",
    "image": "Porker/9_of_clubs.png",
    "description": "Quân bài Chín (9) thuộc chất Tép (Chuồn) (♣) trong bộ bài tây chuẩn 52 lá.",
    "advice": "Mang biểu trưng của chất Tép (Chuồn) (♣) và bậc số Chín (9)."
  },
  {
    "id": 49,
    "code": "10_clubs",
    "name": "Mười (10) Tép (Chuồn) ♣",
    "shortName": "10♣",
    "rank": "Mười (10)",
    "suit": "Tép (Chuồn)",
    "symbol": "♣",
    "color": "Màu đen",
    "image": "Porker/10_of_clubs.png",
    "description": "Quân bài Mười (10) thuộc chất Tép (Chuồn) (♣) trong bộ bài tây chuẩn 52 lá.",
    "advice": "Mang biểu trưng của chất Tép (Chuồn) (♣) và bậc số Mười (10)."
  },
  {
    "id": 50,
    "code": "jack_clubs",
    "name": "J (Jack / Bồi) Tép (Chuồn) ♣",
    "shortName": "J♣",
    "rank": "J (Jack / Bồi)",
    "suit": "Tép (Chuồn)",
    "symbol": "♣",
    "color": "Màu đen",
    "image": "Porker/jack_of_clubs.png",
    "description": "Quân bài J (Jack / Bồi) thuộc chất Tép (Chuồn) (♣) trong bộ bài tây chuẩn 52 lá.",
    "advice": "Mang biểu trưng của chất Tép (Chuồn) (♣) và bậc số J (Jack / Bồi)."
  },
  {
    "id": 51,
    "code": "queen_clubs",
    "name": "Q (Queen / Đầm) Tép (Chuồn) ♣",
    "shortName": "Q♣",
    "rank": "Q (Queen / Đầm)",
    "suit": "Tép (Chuồn)",
    "symbol": "♣",
    "color": "Màu đen",
    "image": "Porker/queen_of_clubs.png",
    "description": "Quân bài Q (Queen / Đầm) thuộc chất Tép (Chuồn) (♣) trong bộ bài tây chuẩn 52 lá.",
    "advice": "Mang biểu trưng của chất Tép (Chuồn) (♣) và bậc số Q (Queen / Đầm)."
  },
  {
    "id": 52,
    "code": "king_clubs",
    "name": "K (King / Già) Tép (Chuồn) ♣",
    "shortName": "K♣",
    "rank": "K (King / Già)",
    "suit": "Tép (Chuồn)",
    "symbol": "♣",
    "color": "Màu đen",
    "image": "Porker/king_of_clubs.png",
    "description": "Quân bài K (King / Già) thuộc chất Tép (Chuồn) (♣) trong bộ bài tây chuẩn 52 lá.",
    "advice": "Mang biểu trưng của chất Tép (Chuồn) (♣) và bậc số K (King / Già)."
  }
];
