/**
 * POKER 52 LÁ - CSDL NGUYÊN VĂN TỪ HÌNH ẢNH TRỰC QUAN TRANG 1 & 2
 * Ý NGHĨA QUÂN BÀI_1.PDF - PHÁP MÔN NADRASA DEHI
 */

const POKER_CARDS_DATA = [
  {
    "id": 1,
    "code": "ace_spades",
    "name": "Át (Ace) Bích ♠",
    "shortName": "A♠",
    "rank": "Át (Ace)",
    "rankNum": 1,
    "rankShort": "A",
    "suit": "Bích",
    "suitCode": "spades",
    "symbol": "♠",
    "color": "Màu đen",
    "colorType": "black",
    "image": "Porker/ace_of_spades.png",
    "meaning": "Các vị thần cõi âm (tầm thấp)/quan thần linh/ Sơn thần",
    "description": "Quân Át (Ace) (♠) mang ý nghĩa: Các vị thần cõi âm (tầm thấp)/quan thần linh/ Sơn thần.",
    "advice": "Quan Thần Linh, Sơn Thần hoặc chư vị thần cõi âm hiển linh hộ quản phương xứ."
  },
  {
    "id": 2,
    "code": "2_spades",
    "name": "Hai (2) Bích ♠",
    "shortName": "2♠",
    "rank": "Hai (2)",
    "rankNum": 2,
    "rankShort": "2",
    "suit": "Bích",
    "suitCode": "spades",
    "symbol": "♠",
    "color": "Màu đen",
    "colorType": "black",
    "image": "Porker/2_of_spades.png",
    "meaning": "Thầy Tà",
    "description": "Quân Hai (2) (♠) mang ý nghĩa: Thầy Tà.",
    "advice": "Cảnh báo sự dẫn dắt sai lạc, tà sư tà đạo hoặc người có tâm địa bất chính gây ảnh hưởng."
  },
  {
    "id": 3,
    "code": "3_spades",
    "name": "Ba (3) Bích ♠",
    "shortName": "3♠",
    "rank": "Ba (3)",
    "rankNum": 3,
    "rankShort": "3",
    "suit": "Bích",
    "suitCode": "spades",
    "symbol": "♠",
    "color": "Màu đen",
    "colorType": "black",
    "image": "Porker/3_of_spades.png",
    "meaning": "Vong trẻ em (thường là nữ)",
    "description": "Quân Ba (3) (♠) mang ý nghĩa: Vong trẻ em (thường là nữ).",
    "advice": "Có sự hiện diện của linh hồn trẻ em (nữ) nương tựa hoặc báo điềm."
  },
  {
    "id": 4,
    "code": "4_spades",
    "name": "Bốn (4) Bích ♠",
    "shortName": "4♠",
    "rank": "Bốn (4)",
    "rankNum": 4,
    "rankShort": "4",
    "suit": "Bích",
    "suitCode": "spades",
    "symbol": "♠",
    "color": "Màu đen",
    "colorType": "black",
    "image": "Porker/4_of_spades.png",
    "meaning": "Âm binh súc sinh. Mộ có vấn đề, động mộ",
    "description": "Quân Bốn (4) (♠) mang ý nghĩa: Âm binh súc sinh. Mộ có vấn đề, động mộ.",
    "advice": "Cảnh báo về phần mộ tổ tiên có dấu hiệu bị động, sụt lún hoặc có âm binh súc sinh quấy nhiễu."
  },
  {
    "id": 5,
    "code": "5_spades",
    "name": "Năm (5) Bích ♠",
    "shortName": "5♠",
    "rank": "Năm (5)",
    "rankNum": 5,
    "rankShort": "5",
    "suit": "Bích",
    "suitCode": "spades",
    "symbol": "♠",
    "color": "Màu đen",
    "colorType": "black",
    "image": "Porker/5_of_spades.png",
    "meaning": "Âm binh người",
    "description": "Quân Năm (5) (♠) mang ý nghĩa: Âm binh người.",
    "advice": "Có âm binh dạng người vướng mắc, theo sát hoặc quấy phá trường năng lượng."
  },
  {
    "id": 6,
    "code": "6_spades",
    "name": "Sáu (6) Bích ♠",
    "shortName": "6♠",
    "rank": "Sáu (6)",
    "rankNum": 6,
    "rankShort": "6",
    "suit": "Bích",
    "suitCode": "spades",
    "symbol": "♠",
    "color": "Màu đen",
    "colorType": "black",
    "image": "Porker/6_of_spades.png",
    "meaning": "Bùa",
    "description": "Quân Sáu (6) (♠) mang ý nghĩa: Bùa.",
    "advice": "Sự hiện diện của bùa chú, tà thuật hoặc trường khí tiêu cực bị gài đặt."
  },
  {
    "id": 7,
    "code": "7_spades",
    "name": "Bảy (7) Bích ♠",
    "shortName": "7♠",
    "rank": "Bảy (7)",
    "rankNum": 7,
    "rankShort": "7",
    "suit": "Bích",
    "suitCode": "spades",
    "symbol": "♠",
    "color": "Màu đen",
    "colorType": "black",
    "image": "Porker/7_of_spades.png",
    "meaning": "Nghiệp tâm linh",
    "description": "Quân Bảy (7) (♠) mang ý nghĩa: Nghiệp tâm linh.",
    "advice": "Khối nghiệp chướng về phần tâm linh tiền kiếp đang đòi hỏi sự sám hối và giải tỏa."
  },
  {
    "id": 8,
    "code": "8_spades",
    "name": "Tám (8) Bích ♠",
    "shortName": "8♠",
    "rank": "Tám (8)",
    "rankNum": 8,
    "rankShort": "8",
    "suit": "Bích",
    "suitCode": "spades",
    "symbol": "♠",
    "color": "Màu đen",
    "colorType": "black",
    "image": "Porker/8_of_spades.png",
    "meaning": "Vong Nữ",
    "description": "Quân Tám (8) (♠) mang ý nghĩa: Vong Nữ.",
    "advice": "Linh hồn nữ giới nơi cõi âm còn nhiều vướng mắc tâm niệm chưa buông."
  },
  {
    "id": 9,
    "code": "9_spades",
    "name": "Chín (9) Bích ♠",
    "shortName": "9♠",
    "rank": "Chín (9)",
    "rankNum": 9,
    "rankShort": "9",
    "suit": "Bích",
    "suitCode": "spades",
    "symbol": "♠",
    "color": "Màu đen",
    "colorType": "black",
    "image": "Porker/9_of_spades.png",
    "meaning": "Vong Nam",
    "description": "Quân Chín (9) (♠) mang ý nghĩa: Vong Nam.",
    "advice": "Linh hồn nam giới nơi cõi âm gửi tín hiệu cần trợ duyên siêu thoát."
  },
  {
    "id": 10,
    "code": "10_spades",
    "name": "Mười (10) Bích ♠",
    "shortName": "10♠",
    "rank": "Mười (10)",
    "rankNum": 10,
    "rankShort": "10",
    "suit": "Bích",
    "suitCode": "spades",
    "symbol": "♠",
    "color": "Màu đen",
    "colorType": "black",
    "image": "Porker/10_of_spades.png",
    "meaning": "Nghiệp ở đất",
    "description": "Quân Mười (10) (♠) mang ý nghĩa: Nghiệp ở đất.",
    "advice": "Năng lượng đất đai, nhà ở đang tích tụ ám khí, nợ nghiệp hoặc tiền duyên chưa dứt."
  },
  {
    "id": 11,
    "code": "jack_spades",
    "name": "J (Jack / Bồi) Bích ♠",
    "shortName": "J♠",
    "rank": "J (Jack / Bồi)",
    "rankNum": 11,
    "rankShort": "J",
    "suit": "Bích",
    "suitCode": "spades",
    "symbol": "♠",
    "color": "Màu đen",
    "colorType": "black",
    "image": "Porker/jack_of_spades.png",
    "meaning": "Thổ địa",
    "description": "Quân J (Jack / Bồi) (♠) mang ý nghĩa: Thổ địa.",
    "advice": "Thần linh Thổ Địa cai quản mảnh đất hiện diện, cần lễ bái tôn kính và giữ sạch long mạch."
  },
  {
    "id": 12,
    "code": "queen_spades",
    "name": "Q (Queen / Đầm) Bích ♠",
    "shortName": "Q♠",
    "rank": "Q (Queen / Đầm)",
    "rankNum": 12,
    "rankShort": "Q",
    "suit": "Bích",
    "suitCode": "spades",
    "symbol": "♠",
    "color": "Màu đen",
    "colorType": "black",
    "image": "Porker/queen_of_spades.png",
    "meaning": "Các vị thần cõi âm (tầm thấp)/ Thổ thần",
    "description": "Quân Q (Queen / Đầm) (♠) mang ý nghĩa: Các vị thần cõi âm (tầm thấp)/ Thổ thần.",
    "advice": "Chư vị thần cõi âm bậc dưới hoặc Thổ thần đang trông coi, chứng giám."
  },
  {
    "id": 13,
    "code": "king_spades",
    "name": "K (King / Già) Bích ♠",
    "shortName": "K♠",
    "rank": "K (King / Già)",
    "rankNum": 13,
    "rankShort": "K",
    "suit": "Bích",
    "suitCode": "spades",
    "symbol": "♠",
    "color": "Màu đen",
    "colorType": "black",
    "image": "Porker/king_of_spades.png",
    "meaning": "Các vị thần cõi âm (tầm thấp)",
    "description": "Quân K (King / Già) (♠) mang ý nghĩa: Các vị thần cõi âm (tầm thấp).",
    "advice": "Chư vị thần cõi âm đang theo dõi mọi hành vi và tâm niệm của trần thế."
  },
  {
    "id": 14,
    "code": "ace_hearts",
    "name": "Át (Ace) Cơ ♥",
    "shortName": "A♥",
    "rank": "Át (Ace)",
    "rankNum": 1,
    "rankShort": "A",
    "suit": "Cơ",
    "suitCode": "hearts",
    "symbol": "♥",
    "color": "Màu đỏ",
    "colorType": "red",
    "image": "Porker/ace_of_hearts.png",
    "meaning": "Các vị tiên thánh cõi cao",
    "description": "Quân Át (Ace) (♥) mang ý nghĩa: Các vị tiên thánh cõi cao.",
    "advice": "Chư vị Tiên Thánh cõi cao chứng giám và soi tỏ mọi việc."
  },
  {
    "id": 15,
    "code": "2_hearts",
    "name": "Hai (2) Cơ ♥",
    "shortName": "2♥",
    "rank": "Hai (2)",
    "rankNum": 2,
    "rankShort": "2",
    "suit": "Cơ",
    "suitCode": "hearts",
    "symbol": "♥",
    "color": "Màu đỏ",
    "colorType": "red",
    "image": "Porker/2_of_hearts.png",
    "meaning": "Thầy chánh pháp",
    "description": "Quân Hai (2) (♥) mang ý nghĩa: Thầy chánh pháp.",
    "advice": "Minh sư chánh pháp chỉ đường dẫn lối, mang năng lượng thanh tịnh."
  },
  {
    "id": 16,
    "code": "3_hearts",
    "name": "Ba (3) Cơ ♥",
    "shortName": "3♥",
    "rank": "Ba (3)",
    "rankNum": 3,
    "rankShort": "3",
    "suit": "Cơ",
    "suitCode": "hearts",
    "symbol": "♥",
    "color": "Màu đỏ",
    "colorType": "red",
    "image": "Porker/3_of_hearts.png",
    "meaning": "Vong trẻ em Nam",
    "description": "Quân Ba (3) (♥) mang ý nghĩa: Vong trẻ em Nam.",
    "advice": "Linh hồn trẻ thơ nam giới hiển hiện mang năng lượng tích cực."
  },
  {
    "id": 17,
    "code": "4_hearts",
    "name": "Bốn (4) Cơ ♥",
    "shortName": "4♥",
    "rank": "Bốn (4)",
    "rankNum": 4,
    "rankShort": "4",
    "suit": "Cơ",
    "suitCode": "hearts",
    "symbol": "♥",
    "color": "Màu đỏ",
    "colorType": "red",
    "image": "Porker/4_of_hearts.png",
    "meaning": "Rồng xuất hiện. Mộ tốt",
    "description": "Quân Bốn (4) (♥) mang ý nghĩa: Rồng xuất hiện. Mộ tốt.",
    "advice": "Long khí hưng thịnh, phần mộ gia tiên được phong thủy tốt lành chở che."
  },
  {
    "id": 18,
    "code": "5_hearts",
    "name": "Năm (5) Cơ ♥",
    "shortName": "5♥",
    "rank": "Năm (5)",
    "rankNum": 5,
    "rankShort": "5",
    "suit": "Cơ",
    "suitCode": "hearts",
    "symbol": "♥",
    "color": "Màu đỏ",
    "colorType": "red",
    "image": "Porker/5_of_hearts.png",
    "meaning": "Con cháu hiếu thảo",
    "description": "Quân Năm (5) (♥) mang ý nghĩa: Con cháu hiếu thảo.",
    "advice": "Đạo hiếu rạng rỡ, phước đức tổ tiên chảy tràn xuống các thế hệ tương lai."
  },
  {
    "id": 19,
    "code": "6_hearts",
    "name": "Sáu (6) Cơ ♥",
    "shortName": "6♥",
    "rank": "Sáu (6)",
    "rankNum": 6,
    "rankShort": "6",
    "suit": "Cơ",
    "suitCode": "hearts",
    "symbol": "♥",
    "color": "Màu đỏ",
    "colorType": "red",
    "image": "Porker/6_of_hearts.png",
    "meaning": "Bùa đã được giải/ Ứng lệnh",
    "description": "Quân Sáu (6) (♥) mang ý nghĩa: Bùa đã được giải/ Ứng lệnh.",
    "advice": "Lệnh giải trừ bùa ngải đã ứng nghiệm, chánh khí phục hồi sáng suốt."
  },
  {
    "id": 20,
    "code": "7_hearts",
    "name": "Bảy (7) Cơ ♥",
    "shortName": "7♥",
    "rank": "Bảy (7)",
    "rankNum": 7,
    "rankShort": "7",
    "suit": "Cơ",
    "suitCode": "hearts",
    "symbol": "♥",
    "color": "Màu đỏ",
    "colorType": "red",
    "image": "Porker/7_of_hearts.png",
    "meaning": "Nghiệp lành",
    "description": "Quân Bảy (7) (♥) mang ý nghĩa: Nghiệp lành.",
    "advice": "Quả ngọt của lòng lương thiện, công đức thiện lương trổ sinh điềm lành."
  },
  {
    "id": 21,
    "code": "8_hearts",
    "name": "Tám (8) Cơ ♥",
    "shortName": "8♥",
    "rank": "Tám (8)",
    "rankNum": 8,
    "rankShort": "8",
    "suit": "Cơ",
    "suitCode": "hearts",
    "symbol": "♥",
    "color": "Màu đỏ",
    "colorType": "red",
    "image": "Porker/8_of_hearts.png",
    "meaning": "Uyển/ Thiên nữ",
    "description": "Quân Tám (8) (♥) mang ý nghĩa: Uyển/ Thiên nữ.",
    "advice": "Chư vị Thiên Nữ thanh cao giáng lâm mang lại trí huệ và sự tươi mới."
  },
  {
    "id": 22,
    "code": "9_hearts",
    "name": "Chín (9) Cơ ♥",
    "shortName": "9♥",
    "rank": "Chín (9)",
    "rankNum": 9,
    "rankShort": "9",
    "suit": "Cơ",
    "suitCode": "hearts",
    "symbol": "♥",
    "color": "Màu đỏ",
    "colorType": "red",
    "image": "Porker/9_of_hearts.png",
    "meaning": "Thiên nam",
    "description": "Quân Chín (9) (♥) mang ý nghĩa: Thiên nam.",
    "advice": "Chư vị Thiên Nam dũng mãnh tiếp thêm nghị lực và bảo vệ thân tâm."
  },
  {
    "id": 23,
    "code": "10_hearts",
    "name": "Mười (10) Cơ ♥",
    "shortName": "10♥",
    "rank": "Mười (10)",
    "rankNum": 10,
    "rankShort": "10",
    "suit": "Cơ",
    "suitCode": "hearts",
    "symbol": "♥",
    "color": "Màu đỏ",
    "colorType": "red",
    "image": "Porker/10_of_hearts.png",
    "meaning": "Thông tin về phủ",
    "description": "Quân Mười (10) (♥) mang ý nghĩa: Thông tin về phủ.",
    "advice": "Tín hiệu tâm linh rõ ràng liên quan đến cửa Phủ và sự việc tâm linh."
  },
  {
    "id": 24,
    "code": "jack_hearts",
    "name": "J (Jack / Bồi) Cơ ♥",
    "shortName": "J♥",
    "rank": "J (Jack / Bồi)",
    "rankNum": 11,
    "rankShort": "J",
    "suit": "Cơ",
    "suitCode": "hearts",
    "symbol": "♥",
    "color": "Màu đỏ",
    "colorType": "red",
    "image": "Porker/jack_of_hearts.png",
    "meaning": "Thần thú",
    "description": "Quân J (Jack / Bồi) (♥) mang ý nghĩa: Thần thú.",
    "advice": "Linh thú hộ trì linh thiêng xua tan u ám, bảo vệ bản thể."
  },
  {
    "id": 25,
    "code": "queen_hearts",
    "name": "Q (Queen / Đầm) Cơ ♥",
    "shortName": "Q♥",
    "rank": "Q (Queen / Đầm)",
    "rankNum": 12,
    "rankShort": "Q",
    "suit": "Cơ",
    "suitCode": "hearts",
    "symbol": "♥",
    "color": "Màu đỏ",
    "colorType": "red",
    "image": "Porker/queen_of_hearts.png",
    "meaning": "Hộ pháp cứu độ",
    "description": "Quân Q (Queen / Đầm) (♥) mang ý nghĩa: Hộ pháp cứu độ.",
    "advice": "Chư vị Hộ Pháp thị hiện tiếp cứu vượt thoát khó khăn, chướng ngại."
  },
  {
    "id": 26,
    "code": "king_hearts",
    "name": "K (King / Già) Cơ ♥",
    "shortName": "K♥",
    "rank": "K (King / Già)",
    "rankNum": 13,
    "rankShort": "K",
    "suit": "Cơ",
    "suitCode": "hearts",
    "symbol": "♥",
    "color": "Màu đỏ",
    "colorType": "red",
    "image": "Porker/king_of_hearts.png",
    "meaning": "Các vị tiên thánh cõi cao",
    "description": "Quân K (King / Già) (♥) mang ý nghĩa: Các vị tiên thánh cõi cao.",
    "advice": "Tiên Thánh thượng giới soi sáng con đường hành đạo và cuộc sống."
  },
  {
    "id": 27,
    "code": "ace_clubs",
    "name": "Át (Ace) Tép (Chuồn) ♣",
    "shortName": "A♣",
    "rank": "Át (Ace)",
    "rankNum": 1,
    "rankShort": "A",
    "suit": "Tép (Chuồn)",
    "suitCode": "clubs",
    "symbol": "♣",
    "color": "Màu đen",
    "colorType": "black",
    "image": "Porker/ace_of_clubs.png",
    "meaning": "Các vị tiên thánh cõi cao",
    "description": "Quân Át (Ace) (♣) mang ý nghĩa: Các vị tiên thánh cõi cao.",
    "advice": "Chư vị Tiên Thánh cõi cao chứng giám và ban phước lành tối cao."
  },
  {
    "id": 28,
    "code": "2_clubs",
    "name": "Hai (2) Tép (Chuồn) ♣",
    "shortName": "2♣",
    "rank": "Hai (2)",
    "rankNum": 2,
    "rankShort": "2",
    "suit": "Tép (Chuồn)",
    "suitCode": "clubs",
    "symbol": "♣",
    "color": "Màu đen",
    "colorType": "black",
    "image": "Porker/2_of_clubs.png",
    "meaning": "Thầy Tà",
    "description": "Quân Hai (2) (♣) mang ý nghĩa: Thầy Tà.",
    "advice": "Cảnh báo tà sư, thầy tà hoặc pháp thuật sai lạc bên ngoài tác động."
  },
  {
    "id": 29,
    "code": "3_clubs",
    "name": "Ba (3) Tép (Chuồn) ♣",
    "shortName": "3♣",
    "rank": "Ba (3)",
    "rankNum": 3,
    "rankShort": "3",
    "suit": "Tép (Chuồn)",
    "suitCode": "clubs",
    "symbol": "♣",
    "color": "Màu đen",
    "colorType": "black",
    "image": "Porker/3_of_clubs.png",
    "meaning": "Vong trẻ em ở ngoài/ Con âm",
    "description": "Quân Ba (3) (♣) mang ý nghĩa: Vong trẻ em ở ngoài/ Con âm.",
    "advice": "Linh hồn trẻ nhỏ lang thang bên ngoài hoặc duyên con âm vương vấn theo gót."
  },
  {
    "id": 30,
    "code": "4_clubs",
    "name": "Bốn (4) Tép (Chuồn) ♣",
    "shortName": "4♣",
    "rank": "Bốn (4)",
    "rankNum": 4,
    "rankShort": "4",
    "suit": "Tép (Chuồn)",
    "suitCode": "clubs",
    "symbol": "♣",
    "color": "Màu đen",
    "colorType": "black",
    "image": "Porker/4_of_clubs.png",
    "meaning": "Âm binh súc sinh. Mất mộ",
    "description": "Quân Bốn (4) (♣) mang ý nghĩa: Âm binh súc sinh. Mất mộ.",
    "advice": "Cảnh báo phần mộ thất lạc, mất dấu tích hoặc âm binh súc sinh quấy phá."
  },
  {
    "id": 31,
    "code": "5_clubs",
    "name": "Năm (5) Tép (Chuồn) ♣",
    "shortName": "5♣",
    "rank": "Năm (5)",
    "rankNum": 5,
    "rankShort": "5",
    "suit": "Tép (Chuồn)",
    "suitCode": "clubs",
    "symbol": "♣",
    "color": "Màu đen",
    "colorType": "black",
    "image": "Porker/5_of_clubs.png",
    "meaning": "Âm binh bên ngoài",
    "description": "Quân Năm (5) (♣) mang ý nghĩa: Âm binh bên ngoài.",
    "advice": "Âm binh từ bên ngoài môi trường quấy nhiễu trường năng lượng của bạn."
  },
  {
    "id": 32,
    "code": "6_clubs",
    "name": "Sáu (6) Tép (Chuồn) ♣",
    "shortName": "6♣",
    "rank": "Sáu (6)",
    "rankNum": 6,
    "rankShort": "6",
    "suit": "Tép (Chuồn)",
    "suitCode": "clubs",
    "symbol": "♣",
    "color": "Màu đen",
    "colorType": "black",
    "image": "Porker/6_of_clubs.png",
    "meaning": "Bùa tàu",
    "description": "Quân Sáu (6) (♣) mang ý nghĩa: Bùa tàu.",
    "advice": "Sự ảnh hưởng của bùa Tàu hoặc các loại huyền thuật ngoại lai thâm hiểm."
  },
  {
    "id": 33,
    "code": "7_clubs",
    "name": "Bảy (7) Tép (Chuồn) ♣",
    "shortName": "7♣",
    "rank": "Bảy (7)",
    "rankNum": 7,
    "rankShort": "7",
    "suit": "Tép (Chuồn)",
    "suitCode": "clubs",
    "symbol": "♣",
    "color": "Màu đen",
    "colorType": "black",
    "image": "Porker/7_of_clubs.png",
    "meaning": "Nghiệp tâm linh",
    "description": "Quân Bảy (7) (♣) mang ý nghĩa: Nghiệp tâm linh.",
    "advice": "Nghiệp quả tâm linh đang hiển lộ, nhắc nhở cần chú trọng tu tâm tích đức."
  },
  {
    "id": 34,
    "code": "8_clubs",
    "name": "Tám (8) Tép (Chuồn) ♣",
    "shortName": "8♣",
    "rank": "Tám (8)",
    "rankNum": 8,
    "rankShort": "8",
    "suit": "Tép (Chuồn)",
    "suitCode": "clubs",
    "symbol": "♣",
    "color": "Màu đen",
    "colorType": "black",
    "image": "Porker/8_of_clubs.png",
    "meaning": "Vong Nữ ở ngoài",
    "description": "Quân Tám (8) (♣) mang ý nghĩa: Vong Nữ ở ngoài.",
    "advice": "Vong hồn nữ giới vãng lai bên ngoài chưa siêu thoát theo bám."
  },
  {
    "id": 35,
    "code": "9_clubs",
    "name": "Chín (9) Tép (Chuồn) ♣",
    "shortName": "9♣",
    "rank": "Chín (9)",
    "rankNum": 9,
    "rankShort": "9",
    "suit": "Tép (Chuồn)",
    "suitCode": "clubs",
    "symbol": "♣",
    "color": "Màu đen",
    "colorType": "black",
    "image": "Porker/9_of_clubs.png",
    "meaning": "Vong Nam ở ngoài",
    "description": "Quân Chín (9) (♣) mang ý nghĩa: Vong Nam ở ngoài.",
    "advice": "Vong hồn nam giới ngoại giới phiêu bạt gửi tín hiệu xin trợ giúp."
  },
  {
    "id": 36,
    "code": "10_clubs",
    "name": "Mười (10) Tép (Chuồn) ♣",
    "shortName": "10♣",
    "rank": "Mười (10)",
    "rankNum": 10,
    "rankShort": "10",
    "suit": "Tép (Chuồn)",
    "suitCode": "clubs",
    "symbol": "♣",
    "color": "Màu đen",
    "colorType": "black",
    "image": "Porker/10_of_clubs.png",
    "meaning": "Nghiệp ở đất khác",
    "description": "Quân Mười (10) (♣) mang ý nghĩa: Nghiệp ở đất khác.",
    "advice": "Nghiệp chướng hoặc duyên nợ liên quan đến mảnh đất phương xa hoặc nơi từng sinh sống."
  },
  {
    "id": 37,
    "code": "jack_clubs",
    "name": "J (Jack / Bồi) Tép (Chuồn) ♣",
    "shortName": "J♣",
    "rank": "J (Jack / Bồi)",
    "rankNum": 11,
    "rankShort": "J",
    "suit": "Tép (Chuồn)",
    "suitCode": "clubs",
    "symbol": "♣",
    "color": "Màu đen",
    "colorType": "black",
    "image": "Porker/jack_of_clubs.png",
    "meaning": "Thổ địa giả/ Thổ địa nữ",
    "description": "Quân J (Jack / Bồi) (♣) mang ý nghĩa: Thổ địa giả/ Thổ địa nữ.",
    "advice": "Cảnh báo hiện tượng Thổ Địa giả danh hoặc sự quấy nhiễu của Thổ Địa nữ."
  },
  {
    "id": 38,
    "code": "queen_clubs",
    "name": "Q (Queen / Đầm) Tép (Chuồn) ♣",
    "shortName": "Q♣",
    "rank": "Q (Queen / Đầm)",
    "rankNum": 12,
    "rankShort": "Q",
    "suit": "Tép (Chuồn)",
    "suitCode": "clubs",
    "symbol": "♣",
    "color": "Màu đen",
    "colorType": "black",
    "image": "Porker/queen_of_clubs.png",
    "meaning": "Quỷ/yêu nữ",
    "description": "Quân Q (Queen / Đầm) (♣) mang ý nghĩa: Quỷ/yêu nữ.",
    "advice": "Thực thể quỷ/yêu nữ gây xáo trộn tinh thần, mê muội cảm xúc."
  },
  {
    "id": 39,
    "code": "king_clubs",
    "name": "K (King / Già) Tép (Chuồn) ♣",
    "shortName": "K♣",
    "rank": "K (King / Già)",
    "rankNum": 13,
    "rankShort": "K",
    "suit": "Tép (Chuồn)",
    "suitCode": "clubs",
    "symbol": "♣",
    "color": "Màu đen",
    "colorType": "black",
    "image": "Porker/king_of_clubs.png",
    "meaning": "Quỷ/yêu nam",
    "description": "Quân K (King / Già) (♣) mang ý nghĩa: Quỷ/yêu nam.",
    "advice": "Thực thể quỷ/yêu nam hung hãn gây tranh chấp, hao tổn nguyên khí."
  },
  {
    "id": 40,
    "code": "ace_diamonds",
    "name": "Át (Ace) Rô ♦",
    "shortName": "A♦",
    "rank": "Át (Ace)",
    "rankNum": 1,
    "rankShort": "A",
    "suit": "Rô",
    "suitCode": "diamonds",
    "symbol": "♦",
    "color": "Màu đỏ",
    "colorType": "red",
    "image": "Porker/ace_of_diamonds.png",
    "meaning": "Ngài Nadrasa Dehi",
    "description": "Quân Át (Ace) (♦) mang ý nghĩa: Ngài Nadrasa Dehi.",
    "advice": "Ân phước tối thượng: Sự hiện diện gia hộ trực tiếp của Đức Bổn Tôn Nadrasa Dehi."
  },
  {
    "id": 41,
    "code": "2_diamonds",
    "name": "Hai (2) Rô ♦",
    "shortName": "2♦",
    "rank": "Hai (2)",
    "rankNum": 2,
    "rankShort": "2",
    "suit": "Rô",
    "suitCode": "diamonds",
    "symbol": "♦",
    "color": "Màu đỏ",
    "colorType": "red",
    "image": "Porker/2_of_diamonds.png",
    "meaning": "Thầy chánh pháp",
    "description": "Quân Hai (2) (♦) mang ý nghĩa: Thầy chánh pháp.",
    "advice": "Minh sư chánh đạo khai mở trí tuệ, dẫn dắt trên con đường tu học chân chính."
  },
  {
    "id": 42,
    "code": "3_diamonds",
    "name": "Ba (3) Rô ♦",
    "shortName": "3♦",
    "rank": "Ba (3)",
    "rankNum": 3,
    "rankShort": "3",
    "suit": "Rô",
    "suitCode": "diamonds",
    "symbol": "♦",
    "color": "Màu đỏ",
    "colorType": "red",
    "image": "Porker/3_of_diamonds.png",
    "meaning": "Vong trẻ em Nam",
    "description": "Quân Ba (3) (♦) mang ý nghĩa: Vong trẻ em Nam.",
    "advice": "Linh hồn trẻ nhỏ nam giới mang tâm niệm trong sáng hướng về gia đình."
  },
  {
    "id": 43,
    "code": "4_diamonds",
    "name": "Bốn (4) Rô ♦",
    "shortName": "4♦",
    "rank": "Bốn (4)",
    "rankNum": 4,
    "rankShort": "4",
    "suit": "Rô",
    "suitCode": "diamonds",
    "symbol": "♦",
    "color": "Màu đỏ",
    "colorType": "red",
    "image": "Porker/4_of_diamonds.png",
    "meaning": "Rồng xuất hiện. Mộ tốt",
    "description": "Quân Bốn (4) (♦) mang ý nghĩa: Rồng xuất hiện. Mộ tốt.",
    "advice": "Điềm lành cát tường: Long mạch hưng vượng, mồ mả tổ tiên kết phát đại cát."
  },
  {
    "id": 44,
    "code": "5_diamonds",
    "name": "Năm (5) Rô ♦",
    "shortName": "5♦",
    "rank": "Năm (5)",
    "rankNum": 5,
    "rankShort": "5",
    "suit": "Rô",
    "suitCode": "diamonds",
    "symbol": "♦",
    "color": "Màu đỏ",
    "colorType": "red",
    "image": "Porker/5_of_diamonds.png",
    "meaning": "Con cháu hiếu thảo",
    "description": "Quân Năm (5) (♦) mang ý nghĩa: Con cháu hiếu thảo.",
    "advice": "Gia đạo thuận hòa, con cháu thảo hiền biết hướng về cội nguồn tổ tiên."
  },
  {
    "id": 45,
    "code": "6_diamonds",
    "name": "Sáu (6) Rô ♦",
    "shortName": "6♦",
    "rank": "Sáu (6)",
    "rankNum": 6,
    "rankShort": "6",
    "suit": "Rô",
    "suitCode": "diamonds",
    "symbol": "♦",
    "color": "Màu đỏ",
    "colorType": "red",
    "image": "Porker/6_of_diamonds.png",
    "meaning": "Phúc lành. Bùa đã được giải",
    "description": "Quân Sáu (6) (♦) mang ý nghĩa: Phúc lành. Bùa đã được giải.",
    "advice": "Phước đức sâu dày: Bùa chú tà thuật đã được hóa giải hoàn toàn, thân tâm an lạc."
  },
  {
    "id": 46,
    "code": "7_diamonds",
    "name": "Bảy (7) Rô ♦",
    "shortName": "7♦",
    "rank": "Bảy (7)",
    "rankNum": 7,
    "rankShort": "7",
    "suit": "Rô",
    "suitCode": "diamonds",
    "symbol": "♦",
    "color": "Màu đỏ",
    "colorType": "red",
    "image": "Porker/7_of_diamonds.png",
    "meaning": "Nghiệp lành",
    "description": "Quân Bảy (7) (♦) mang ý nghĩa: Nghiệp lành.",
    "advice": "Thiện căn tích tụ trổ quả ngọt ngào, may mắn hanh thông trong cuộc sống."
  },
  {
    "id": 47,
    "code": "8_diamonds",
    "name": "Tám (8) Rô ♦",
    "shortName": "8♦",
    "rank": "Tám (8)",
    "rankNum": 8,
    "rankShort": "8",
    "suit": "Rô",
    "suitCode": "diamonds",
    "symbol": "♦",
    "color": "Màu đỏ",
    "colorType": "red",
    "image": "Porker/8_of_diamonds.png",
    "meaning": "Bồ tát/ Quan thế âm Bồ Tát/ Vong nữ gia tiên",
    "description": "Quân Tám (8) (♦) mang ý nghĩa: Bồ tát/ Quan thế âm Bồ Tát/ Vong nữ gia tiên.",
    "advice": "Đức Quán Thế Âm Bồ Tát hoặc vong nữ gia tiên từ bi phóng quang gia hộ che chở."
  },
  {
    "id": 48,
    "code": "9_diamonds",
    "name": "Chín (9) Rô ♦",
    "shortName": "9♦",
    "rank": "Chín (9)",
    "rankNum": 9,
    "rankShort": "9",
    "suit": "Rô",
    "suitCode": "diamonds",
    "symbol": "♦",
    "color": "Màu đỏ",
    "colorType": "red",
    "image": "Porker/9_of_diamonds.png",
    "meaning": "Bà tổ cô",
    "description": "Quân Chín (9) (♦) mang ý nghĩa: Bà tổ cô.",
    "advice": "Bà Tổ Cô linh thiêng trong dòng họ chở che, độ trì vượt qua sóng gió."
  },
  {
    "id": 49,
    "code": "10_diamonds",
    "name": "Mười (10) Rô ♦",
    "shortName": "10♦",
    "rank": "Mười (10)",
    "rankNum": 10,
    "rankShort": "10",
    "suit": "Rô",
    "suitCode": "diamonds",
    "symbol": "♦",
    "color": "Màu đỏ",
    "colorType": "red",
    "image": "Porker/10_of_diamonds.png",
    "meaning": "Phủ",
    "description": "Quân Mười (10) (♦) mang ý nghĩa: Phủ.",
    "advice": "Nơi cửa Phủ linh thiêng, gắn liền với căn số và sự che chở của Thánh Mẫu."
  },
  {
    "id": 50,
    "code": "jack_diamonds",
    "name": "J (Jack / Bồi) Rô ♦",
    "shortName": "J♦",
    "rank": "J (Jack / Bồi)",
    "rankNum": 11,
    "rankShort": "J",
    "suit": "Rô",
    "suitCode": "diamonds",
    "symbol": "♦",
    "color": "Màu đỏ",
    "colorType": "red",
    "image": "Porker/jack_of_diamonds.png",
    "meaning": "Ông mãnh",
    "description": "Quân J (Jack / Bồi) (♦) mang ý nghĩa: Ông mãnh.",
    "advice": "Ông Mãnh hiển linh độ trì cho con cháu trong dòng tộc bình an, công việc thuận lợi."
  },
  {
    "id": 51,
    "code": "queen_diamonds",
    "name": "Q (Queen / Đầm) Rô ♦",
    "shortName": "Q♦",
    "rank": "Q (Queen / Đầm)",
    "rankNum": 12,
    "rankShort": "Q",
    "suit": "Rô",
    "suitCode": "diamonds",
    "symbol": "♦",
    "color": "Màu đỏ",
    "colorType": "red",
    "image": "Porker/queen_of_diamonds.png",
    "meaning": "Hộ pháp Thiên tâm đạo/ Gia tiên",
    "description": "Quân Q (Queen / Đầm) (♦) mang ý nghĩa: Hộ pháp Thiên tâm đạo/ Gia tiên.",
    "advice": "Chư vị Hộ Pháp Thiên Tâm Đạo và Tiên Tổ đồng hành hộ trì vững chắc."
  },
  {
    "id": 52,
    "code": "king_diamonds",
    "name": "K (King / Già) Rô ♦",
    "shortName": "K♦",
    "rank": "K (King / Già)",
    "rankNum": 13,
    "rankShort": "K",
    "suit": "Rô",
    "suitCode": "diamonds",
    "symbol": "♦",
    "color": "Màu đỏ",
    "colorType": "red",
    "image": "Porker/king_of_diamonds.png",
    "meaning": "Thiên thần hộ mệnh/ Vị thánh cấp cao",
    "description": "Quân K (King / Già) (♦) mang ý nghĩa: Thiên thần hộ mệnh/ Vị thánh cấp cao.",
    "advice": "Thiên thần bảo hộ và chư vị Thánh thượng giới phóng quang dẫn lối."
  }
];

const POKER_COMBOS_DATA = [
  {
    "id": "combo_2_6_3",
    "ranks": [
      2,
      6,
      3
    ],
    "color": "any",
    "suit": "any",
    "name": "Bộ 2 - 6 - 3",
    "meaning": "Lắng nghe thông tin từ các vị",
    "description": "Lắng nghe thông tin từ các vị."
  },
  {
    "id": "combo_5_7_8_black",
    "ranks": [
      5,
      7,
      8
    ],
    "color": "black",
    "suit": "any",
    "name": "Bộ 5 - 7 - 8 Đen",
    "meaning": "Nghiệp nặng",
    "description": "Nghiệp nặng."
  },
  {
    "id": "combo_5_7_8_red",
    "ranks": [
      5,
      7,
      8
    ],
    "color": "red",
    "suit": "any",
    "name": "Bộ 5 - 7 - 8 Đỏ",
    "meaning": "Xác nhận từ các vị hộ pháp",
    "description": "Xác nhận từ các vị hộ pháp."
  },
  {
    "id": "combo_4_6_3",
    "ranks": [
      4,
      6,
      3
    ],
    "color": "any",
    "suit": "any",
    "name": "Bộ 4 - 6 - 3",
    "meaning": "Vong muốn nói chuyện",
    "description": "Vong muốn nói chuyện."
  },
  {
    "id": "combo_2_7_9",
    "ranks": [
      2,
      7,
      9
    ],
    "color": "any",
    "suit": "any",
    "name": "Bộ 2 - 7 - 9",
    "meaning": "Quỷ nam phúc mỏng",
    "description": "Quỷ nam phúc mỏng."
  },
  {
    "id": "combo_2_6_9",
    "ranks": [
      2,
      6,
      9
    ],
    "color": "any",
    "suit": "any",
    "name": "Bộ 2 - 6 - 9",
    "meaning": "Quỷ nữ phúc mỏng",
    "description": "Quỷ nữ phúc mỏng."
  },
  {
    "id": "combo_6_7_9",
    "ranks": [
      6,
      7,
      9
    ],
    "color": "any",
    "suit": "any",
    "name": "Bộ 6 - 7 - 9",
    "meaning": "Thiếu thông tin",
    "description": "Thiếu thông tin."
  },
  {
    "id": "combo_7_6_3",
    "ranks": [
      7,
      6,
      3
    ],
    "color": "any",
    "suit": "any",
    "name": "Bộ 7 - 6 - 3",
    "meaning": "Vong muốn tấn công",
    "description": "Vong muốn tấn công."
  },
  {
    "id": "combo_5_6_8_ro",
    "ranks": [
      5,
      6,
      8
    ],
    "color": "any",
    "suit": "diamonds",
    "name": "Bộ 5 - 6 - 8 Rô ♦",
    "meaning": "Xác nhận/ chỉ dẫn từ bồ tát",
    "description": "Xác nhận/ chỉ dẫn từ bồ tát."
  },
  {
    "id": "combo_5_6_8",
    "ranks": [
      5,
      6,
      8
    ],
    "color": "any",
    "suit": "any",
    "name": "Bộ 5 - 6 - 8",
    "meaning": "Tác ý và tri giác đang đúng/ Xác nhận",
    "description": "Tác ý và tri giác đang đúng/ Xác nhận."
  },
  {
    "id": "combo_4_8_9",
    "ranks": [
      4,
      8,
      9
    ],
    "color": "any",
    "suit": "any",
    "name": "Bộ 4 - 8 - 9",
    "meaning": "Thực thể linh hồn ký sinh trong cơ thể",
    "description": "Báo hiệu có 1 thực thể bất kỳ nào đó dạng linh hồn (súc sinh - ấu trùng) có ý thức, có bản ngã - đang ký sinh trong cơ thể và điều khiển hoặc nương nhờ năng lượng con người để làm việc của chúng mong muốn."
  },
  {
    "id": "combo_5_7_9",
    "ranks": [
      5,
      7,
      9
    ],
    "color": "any",
    "suit": "any",
    "name": "Bộ 5 - 7 - 9",
    "meaning": "Âm binh và vong ký sinh trong người",
    "description": "Âm binh và vong nói chung (ko phân biệt nam nữ) ký sinh ở trong người."
  },
  {
    "id": "combo_5_6_3",
    "ranks": [
      5,
      6,
      3
    ],
    "color": "any",
    "suit": "any",
    "name": "Bộ 5 - 6 - 3",
    "meaning": "Nợ nghiệp",
    "description": "Nợ nghiệp."
  },
  {
    "id": "combo_4_9_5",
    "ranks": [
      4,
      9,
      5
    ],
    "color": "any",
    "suit": "any",
    "name": "Bộ 4 - 9 - 5",
    "meaning": "Gia tiên báo việc âm",
    "description": "Gia tiên báo việc âm (thông thường là đang bị âm binh, yêu quỷ quấy phá, hoặc bất kể việc gì mà họ đang hoảng sợ cần cứu giúp)."
  },
  {
    "id": "combo_2_4_9",
    "ranks": [
      2,
      4,
      9
    ],
    "color": "any",
    "suit": "any",
    "name": "Bộ 2 - 4 - 9",
    "meaning": "Thông tin giả",
    "description": "Thông tin giả."
  },
  {
    "id": "combo_3_6_9",
    "ranks": [
      3,
      6,
      9
    ],
    "color": "any",
    "suit": "any",
    "name": "Bộ 3 - 6 - 9",
    "meaning": "Nhận được sự gia hộ / Thông pháp / Lời nhắc nhở",
    "description": "Bạn đang nhận được sự gia hộ. Cũng là thông pháp, nhưng kèm theo lời nhắc nhở về sự thiếu tập trung, chưa tinh tấn, cần cố gắng hơn nữa để bắt kịp với tư tưởng hành pháp trong kênh dẫn (nhắc nhở đang tà kiến và cẩn thận sẽ hành ác pháp)."
  }
];

const NADRASA_NUMBERS_DATA = [
  {
    "code": "221",
    "meaning": "Nhiều trắc trở sắp xảy ra về tiền bạc, sức khỏe"
  },
  {
    "code": "222",
    "meaning": "Sự xuất hiện của thiên thần bảo hộ bất kể khi nào bạn kêu gọi"
  },
  {
    "code": "223",
    "meaning": "Hãy thiền nhận năng lượng bảo vệ"
  },
  {
    "code": "224",
    "meaning": "Kiềm chế và rèn luyện kiên nhẫn, cẩn thận tổn thương"
  },
  {
    "code": "225",
    "meaning": "Sự mất mát nào đó sớm xảy ra"
  },
  {
    "code": "226",
    "meaning": "Có nghiệp đang quanh bạn, và sẽ trổ ra sắp tơi hoặc bây giờ."
  },
  {
    "code": "227",
    "meaning": "Linh hồn của bạn đang trong kết nối với vị thầy Bổn Tôn (Nadrasa Dehi)."
  },
  {
    "code": "228",
    "meaning": "Sự bảo hộ của các vị Hộ Pháp dành cho bạn"
  },
  {
    "code": "229",
    "meaning": "Hãy buông bỏ các bám chấp và quên đi nỗi đau buồn của quá khứ. Sống với thực tại."
  },
  {
    "code": "220",
    "meaning": "Sự cố về họa mắt và họa miệng rất dễ xảy ra giữ vững thái độ ôn hòa trong mọi tình huống."
  },
  {
    "code": "77",
    "meaning": "Nhắc nhở hãy tin tưởng vào sức mạnh tâm linh của bản thân"
  },
  {
    "code": "777",
    "meaning": "Hãy tập trung lắng nghe sự dẫn dắt ngay bây giờ, đọc trong suy nghĩ của bạn sẽ nghe thấy lời chỉ dẫn."
  },
  {
    "code": "7777",
    "meaning": "Hãy bước ra ánh sáng (hãy làm việc), để cho sự dẫn dắt được xảy ra cùng lúc với bạn trong những trải nghiệm."
  },
  {
    "code": "77777",
    "meaning": "Bất kể điều gì bạn đang nghĩ đều đúng!"
  }
];
