const POKER_CARDS_DATA = [
  {
    "id": 1,
    "code": "ace_spades",
    "name": "Át (Ace) Bích ♠",
    "shortName": "A♠",
    "rank": "Át (Ace)",
    "rankNum": 1,
    "rankShort": "A",
    "suit": "Bích",
    "suitCode": "spades",
    "symbol": "♠",
    "color": "Màu đen",
    "colorType": "black",
    "image": "Porker/ace_of_spades.png",
    "symbolCode": "b",
    "meaning": "Thầy Tà",
    "description": "Quân Át (Ace) (♠) mang ý nghĩa: Thầy Tà.",
    "advice": "Cảnh báo sự dẫn dắt sai lạc, tà sư tà đạo hoặc người có tâm địa bất chính gây ảnh hưởng."
  },
  {
    "id": 2,
    "code": "2_spades",
    "name": "Hai (2) Bích ♠",
    "shortName": "2♠",
    "rank": "Hai (2)",
    "rankNum": 2,
    "rankShort": "2",
    "suit": "Bích",
    "suitCode": "spades",
    "symbol": "♠",
    "color": "Màu đen",
    "colorType": "black",
    "image": "Porker/2_of_spades.png",
    "symbolCode": "c",
    "meaning": "Vong trẻ em (thường là nữ)",
    "description": "Quân Hai (2) (♠) mang ý nghĩa: Vong trẻ em (thường là nữ).",
    "advice": "Có sự hiện diện của linh hồn trẻ em (nữ) nương tựa hoặc báo điềm."
  },
  {
    "id": 3,
    "code": "3_spades",
    "name": "Ba (3) Bích ♠",
    "shortName": "3♠",
    "rank": "Ba (3)",
    "rankNum": 3,
    "rankShort": "3",
    "suit": "Bích",
    "suitCode": "spades",
    "symbol": "♠",
    "color": "Màu đen",
    "colorType": "black",
    "image": "Porker/3_of_spades.png",
    "symbolCode": "d",
    "meaning": "Âm binh súc sinh. Mộ có vấn đề, động mộ",
    "description": "Quân Ba (3) (♠) mang ý nghĩa: Âm binh súc sinh. Mộ có vấn đề, động mộ.",
    "advice": "Cảnh báo về phần mộ tổ tiên có dấu hiệu bị động, sụt lún hoặc có âm binh súc sinh quấy nhiễu."
  },
  {
    "id": 4,
    "code": "4_spades",
    "name": "Bốn (4) Bích ♠",
    "shortName": "4♠",
    "rank": "Bốn (4)",
    "rankNum": 4,
    "rankShort": "4",
    "suit": "Bích",
    "suitCode": "spades",
    "symbol": "♠",
    "color": "Màu đen",
    "colorType": "black",
    "image": "Porker/4_of_spades.png",
    "symbolCode": "e",
    "meaning": "Âm binh người",
    "description": "Quân Bốn (4) (♠) mang ý nghĩa: Âm binh người.",
    "advice": "Có âm binh dạng người vướng mắc, theo sát hoặc quấy phá trường năng lượng."
  },
  {
    "id": 5,
    "code": "5_spades",
    "name": "Năm (5) Bích ♠",
    "shortName": "5♠",
    "rank": "Năm (5)",
    "rankNum": 5,
    "rankShort": "5",
    "suit": "Bích",
    "suitCode": "spades",
    "symbol": "♠",
    "color": "Màu đen",
    "colorType": "black",
    "image": "Porker/5_of_spades.png",
    "symbolCode": "f",
    "meaning": "Bùa",
    "description": "Quân Năm (5) (♠) mang ý nghĩa: Bùa.",
    "advice": "Sự hiện diện của bùa chú, tà thuật hoặc trường khí tiêu cực bị gài đặt."
  },
  {
    "id": 6,
    "code": "6_spades",
    "name": "Sáu (6) Bích ♠",
    "shortName": "6♠",
    "rank": "Sáu (6)",
    "rankNum": 6,
    "rankShort": "6",
    "suit": "Bích",
    "suitCode": "spades",
    "symbol": "♠",
    "color": "Màu đen",
    "colorType": "black",
    "image": "Porker/6_of_spades.png",
    "symbolCode": "g",
    "meaning": "Nghiệp tâm linh",
    "description": "Quân Sáu (6) (♠) mang ý nghĩa: Nghiệp tâm linh.",
    "advice": "Khối nghiệp chướng về phần tâm linh tiền kiếp đang đòi hỏi sự sám hối và giải tỏa."
  },
  {
    "id": 7,
    "code": "7_spades",
    "name": "Bảy (7) Bích ♠",
    "shortName": "7♠",
    "rank": "Bảy (7)",
    "rankNum": 7,
    "rankShort": "7",
    "suit": "Bích",
    "suitCode": "spades",
    "symbol": "♠",
    "color": "Màu đen",
    "colorType": "black",
    "image": "Porker/7_of_spades.png",
    "symbolCode": "h",
    "meaning": "Vong Nữ",
    "description": "Quân Bảy (7) (♠) mang ý nghĩa: Vong Nữ.",
    "advice": "Linh hồn nữ giới nơi cõi âm còn nhiều vướng mắc tâm niệm chưa buông."
  },
  {
    "id": 8,
    "code": "8_spades",
    "name": "Tám (8) Bích ♠",
    "shortName": "8♠",
    "rank": "Tám (8)",
    "rankNum": 8,
    "rankShort": "8",
    "suit": "Bích",
    "suitCode": "spades",
    "symbol": "♠",
    "color": "Màu đen",
    "colorType": "black",
    "image": "Porker/8_of_spades.png",
    "symbolCode": "i",
    "meaning": "Vong Nam",
    "description": "Quân Tám (8) (♠) mang ý nghĩa: Vong Nam.",
    "advice": "Linh hồn nam giới nơi cõi âm gửi tín hiệu cần trợ duyên siêu thoát."
  },
  {
    "id": 9,
    "code": "9_spades",
    "name": "Chín (9) Bích ♠",
    "shortName": "9♠",
    "rank": "Chín (9)",
    "rankNum": 9,
    "rankShort": "9",
    "suit": "Bích",
    "suitCode": "spades",
    "symbol": "♠",
    "color": "Màu đen",
    "colorType": "black",
    "image": "Porker/9_of_spades.png",
    "symbolCode": "j",
    "meaning": "Nghiệp ở đất",
    "description": "Quân Chín (9) (♠) mang ý nghĩa: Nghiệp ở đất.",
    "advice": "Ân oán hoặc nghiệp nợ xảy ra trên thửa đất hiện tại đang tác động đến gia chủ."
  },
  {
    "id": 10,
    "code": "10_spades",
    "name": "Mười (10) Bích ♠",
    "shortName": "10♠",
    "rank": "Mười (10)",
    "rankNum": 10,
    "rankShort": "10",
    "suit": "Bích",
    "suitCode": "spades",
    "symbol": "♠",
    "color": "Màu đen",
    "colorType": "black",
    "image": "Porker/10_of_spades.png",
    "symbolCode": "k",
    "meaning": "Thổ địa",
    "description": "Quân Mười (10) (♠) mang ý nghĩa: Thổ địa.",
    "advice": "Vị Thổ Thần cai quản đất đai bản xứ; báo hiệu cần chú trọng cúng lễ, hòa hợp long mạch."
  },
  {
    "id": 11,
    "code": "jack_spades",
    "name": "J (Jack / Bồi) Bích ♠",
    "shortName": "J♠",
    "rank": "J (Jack / Bồi)",
    "rankNum": 11,
    "rankShort": "J",
    "suit": "Bích",
    "suitCode": "spades",
    "symbol": "♠",
    "color": "Màu đen",
    "colorType": "black",
    "image": "Porker/jack_of_spades.png",
    "symbolCode": "l",
    "meaning": "Các vị thần cõi âm (tầm thấp) / Thổ thần",
    "description": "Quân J (Jack / Bồi) (♠) mang ý nghĩa: Các vị thần cõi âm (tầm thấp) / Thổ thần.",
    "advice": "Sự hiện diện của chư vị thần cõi âm bậc thấp hoặc Thổ Thần địa phương."
  },
  {
    "id": 12,
    "code": "queen_spades",
    "name": "Q (Queen / Đầm) Bích ♠",
    "shortName": "Q♠",
    "rank": "Q (Queen / Đầm)",
    "rankNum": 12,
    "rankShort": "Q",
    "suit": "Bích",
    "suitCode": "spades",
    "symbol": "♠",
    "color": "Màu đen",
    "colorType": "black",
    "image": "Porker/queen_of_spades.png",
    "symbolCode": "m",
    "meaning": "Các vị thần cõi âm (tầm thấp)",
    "description": "Quân Q (Queen / Đầm) (♠) mang ý nghĩa: Các vị thần cõi âm (tầm thấp).",
    "advice": "Năng lượng thần linh cõi âm tầm thấp nhắc nhở lễ nghi gia trạch."
  },
  {
    "id": 13,
    "code": "king_spades",
    "name": "K (King / Già) Bích ♠",
    "shortName": "K♠",
    "rank": "K (King / Già)",
    "rankNum": 13,
    "rankShort": "K",
    "suit": "Bích",
    "suitCode": "spades",
    "symbol": "♠",
    "color": "Màu đen",
    "colorType": "black",
    "image": "Porker/king_of_spades.png",
    "symbolCode": "a",
    "meaning": "Các vị thần cõi âm (tầm thấp) / Quan thần linh / Sơn thần",
    "description": "Quân K (King / Già) (♠) mang ý nghĩa: Các vị thần cõi âm (tầm thấp) / Quan thần linh / Sơn thần.",
    "advice": "Chư vị Quan Thần Linh hoặc Sơn Thần bản xứ soi xét hành vi và tâm đức."
  },
  {
    "id": 14,
    "code": "ace_hearts",
    "name": "Át (Ace) Cơ ♥",
    "shortName": "A♥",
    "rank": "Át (Ace)",
    "rankNum": 1,
    "rankShort": "A",
    "suit": "Cơ",
    "suitCode": "hearts",
    "symbol": "♥",
    "color": "Màu đỏ",
    "colorType": "red",
    "image": "Porker/ace_of_hearts.png",
    "symbolCode": "B",
    "meaning": "Thầy chánh pháp",
    "description": "Quân Át (Ace) (♥) mang ý nghĩa: Thầy chánh pháp.",
    "advice": "Được dẫn dắt bởi minh sư chân chính, chánh pháp quang minh soi rọi."
  },
  {
    "id": 15,
    "code": "2_hearts",
    "name": "Hai (2) Cơ ♥",
    "shortName": "2♥",
    "rank": "Hai (2)",
    "rankNum": 2,
    "rankShort": "2",
    "suit": "Cơ",
    "suitCode": "hearts",
    "symbol": "♥",
    "color": "Màu đỏ",
    "colorType": "red",
    "image": "Porker/2_of_hearts.png",
    "symbolCode": "C",
    "meaning": "Vong trẻ em Nam",
    "description": "Quân Hai (2) (♥) mang ý nghĩa: Vong trẻ em Nam.",
    "advice": "Chân linh trẻ em nam có duyên lành, con cháu nơi cõi vô hình che chở."
  },
  {
    "id": 16,
    "code": "3_hearts",
    "name": "Ba (3) Cơ ♥",
    "shortName": "3♥",
    "rank": "Ba (3)",
    "rankNum": 3,
    "rankShort": "3",
    "suit": "Cơ",
    "suitCode": "hearts",
    "symbol": "♥",
    "color": "Màu đỏ",
    "colorType": "red",
    "image": "Porker/3_of_hearts.png",
    "symbolCode": "D",
    "meaning": "Rồng xuất hiện. Mộ tốt",
    "description": "Quân Ba (3) (♥) mang ý nghĩa: Rồng xuất hiện. Mộ tốt.",
    "advice": "Điềm lành đại cát: Long mạch quy tụ, mồ mả tổ tiên kết phát vượng khí."
  },
  {
    "id": 17,
    "code": "4_hearts",
    "name": "Bốn (4) Cơ ♥",
    "shortName": "4♥",
    "rank": "Bốn (4)",
    "rankNum": 4,
    "rankShort": "4",
    "suit": "Cơ",
    "suitCode": "hearts",
    "symbol": "♥",
    "color": "Màu đỏ",
    "colorType": "red",
    "image": "Porker/4_of_hearts.png",
    "symbolCode": "E",
    "meaning": "Con cháu hiếu thảo",
    "description": "Quân Bốn (4) (♥) mang ý nghĩa: Con cháu hiếu thảo.",
    "advice": "Phúc đức gia đình hưng thịnh, con cháu hiếu thuận, hòa khí sinh tài."
  },
  {
    "id": 18,
    "code": "5_hearts",
    "name": "Năm (5) Cơ ♥",
    "shortName": "5♥",
    "rank": "Năm (5)",
    "rankNum": 5,
    "rankShort": "5",
    "suit": "Cơ",
    "suitCode": "hearts",
    "symbol": "♥",
    "color": "Màu đỏ",
    "colorType": "red",
    "image": "Porker/5_of_hearts.png",
    "symbolCode": "F",
    "meaning": "Phúc lành. Bùa đã được giải",
    "description": "Quân Năm (5) (♥) mang ý nghĩa: Phúc lành. Bùa đã được giải.",
    "advice": "Phước báu tròn đầy, mọi tà thuật hay ách nạn bùa chú đều đã được giải hóa tiêu tan."
  },
  {
    "id": 19,
    "code": "6_hearts",
    "name": "Sáu (6) Cơ ♥",
    "shortName": "6♥",
    "rank": "Sáu (6)",
    "rankNum": 6,
    "rankShort": "6",
    "suit": "Cơ",
    "suitCode": "hearts",
    "symbol": "♥",
    "color": "Màu đỏ",
    "colorType": "red",
    "image": "Porker/6_of_hearts.png",
    "symbolCode": "G",
    "meaning": "Nghiệp lành",
    "description": "Quân Sáu (6) (♥) mang ý nghĩa: Nghiệp lành.",
    "advice": "Hạt giống thiện lành trổ quả cát tường, đón nhận thuận duyên và an vui."
  },
  {
    "id": 20,
    "code": "7_hearts",
    "name": "Bảy (7) Cơ ♥",
    "shortName": "7♥",
    "rank": "Bảy (7)",
    "rankNum": 7,
    "rankShort": "7",
    "suit": "Cơ",
    "suitCode": "hearts",
    "symbol": "♥",
    "color": "Màu đỏ",
    "colorType": "red",
    "image": "Porker/7_of_hearts.png",
    "symbolCode": "H",
    "meaning": "Bồ tát / Quan Thế Âm Bồ Tát / Vong nữ gia tiên",
    "description": "Quân Bảy (7) (♥) mang ý nghĩa: Bồ tát / Quan Thế Âm Bồ Tát / Vong nữ gia tiên.",
    "advice": "Được Đức Quán Thế Âm Bồ Tát từ bi gia hộ hoặc vong nữ tiền nhân phù hộ độ trì."
  },
  {
    "id": 21,
    "code": "8_hearts",
    "name": "Tám (8) Cơ ♥",
    "shortName": "8♥",
    "rank": "Tám (8)",
    "rankNum": 8,
    "rankShort": "8",
    "suit": "Cơ",
    "suitCode": "hearts",
    "symbol": "♥",
    "color": "Màu đỏ",
    "colorType": "red",
    "image": "Porker/8_of_hearts.png",
    "symbolCode": "I",
    "meaning": "Bà tổ cô",
    "description": "Quân Tám (8) (♥) mang ý nghĩa: Bà tổ cô.",
    "advice": "Bà Cô Tổ dòng họ linh thiêng đang theo sát che chở cho cháu con trong dòng tộc."
  },
  {
    "id": 22,
    "code": "9_hearts",
    "name": "Chín (9) Cơ ♥",
    "shortName": "9♥",
    "rank": "Chín (9)",
    "rankNum": 9,
    "rankShort": "9",
    "suit": "Cơ",
    "suitCode": "hearts",
    "symbol": "♥",
    "color": "Màu đỏ",
    "colorType": "red",
    "image": "Porker/9_of_hearts.png",
    "symbolCode": "J",
    "meaning": "Phủ",
    "description": "Quân Chín (9) (♥) mang ý nghĩa: Phủ.",
    "advice": "Thông tin liên quan đến Phủ Mẫu, cửa Tiên, nơi linh thiêng tâm linh gia trì."
  },
  {
    "id": 23,
    "code": "10_hearts",
    "name": "Mười (10) Cơ ♥",
    "shortName": "10♥",
    "rank": "Mười (10)",
    "rankNum": 10,
    "rankShort": "10",
    "suit": "Cơ",
    "suitCode": "hearts",
    "symbol": "♥",
    "color": "Màu đỏ",
    "colorType": "red",
    "image": "Porker/10_of_hearts.png",
    "symbolCode": "K",
    "meaning": "Ông mãnh",
    "description": "Quân Mười (10) (♥) mang ý nghĩa: Ông mãnh.",
    "advice": "Ông Mãnh dòng họ thị hiện bảo bọc, dẫn đường chỉ lối vượt qua thử thách."
  },
  {
    "id": 24,
    "code": "jack_hearts",
    "name": "J (Jack / Bồi) Cơ ♥",
    "shortName": "J♥",
    "rank": "J (Jack / Bồi)",
    "rankNum": 11,
    "rankShort": "J",
    "suit": "Cơ",
    "suitCode": "hearts",
    "symbol": "♥",
    "color": "Màu đỏ",
    "colorType": "red",
    "image": "Porker/jack_of_hearts.png",
    "symbolCode": "L",
    "meaning": "Hộ pháp Thiên tâm đạo / Gia tiên",
    "description": "Quân J (Jack / Bồi) (♥) mang ý nghĩa: Hộ pháp Thiên tâm đạo / Gia tiên.",
    "advice": "Chư vị Hộ Pháp của Thiên Tâm Đạo và cửu huyền thất tổ đồng tâm hộ trì."
  },
  {
    "id": 25,
    "code": "queen_hearts",
    "name": "Q (Queen / Đầm) Cơ ♥",
    "shortName": "Q♥",
    "rank": "Q (Queen / Đầm)",
    "rankNum": 12,
    "rankShort": "Q",
    "suit": "Cơ",
    "suitCode": "hearts",
    "symbol": "♥",
    "color": "Màu đỏ",
    "colorType": "red",
    "image": "Porker/queen_of_hearts.png",
    "symbolCode": "M",
    "meaning": "Thiên thần hộ mệnh / Vị thánh cấp cao",
    "description": "Quân Q (Queen / Đầm) (♥) mang ý nghĩa: Thiên thần hộ mệnh / Vị thánh cấp cao.",
    "advice": "Thiên thần bản mệnh và chư vị Thánh chúng cõi cao đang chiếu sáng bảo vệ bạn."
  },
  {
    "id": 26,
    "code": "king_hearts",
    "name": "K (King / Già) Cơ ♥",
    "shortName": "K♥",
    "rank": "K (King / Già)",
    "rankNum": 13,
    "rankShort": "K",
    "suit": "Cơ",
    "suitCode": "hearts",
    "symbol": "♥",
    "color": "Màu đỏ",
    "colorType": "red",
    "image": "Porker/king_of_hearts.png",
    "symbolCode": "A",
    "meaning": "Ngài Nadrasa Dehi",
    "description": "Quân K (King / Già) (♥) mang ý nghĩa: Ngài Nadrasa Dehi.",
    "advice": "Kết nối tối thượng với Đấng Tối Cao Nadrasa Dehi - Ánh sáng Chân Lý vô lượng."
  },
  {
    "id": 27,
    "code": "ace_clubs",
    "name": "Át (Ace) Tép (Chuồn) ♣",
    "shortName": "A♣",
    "rank": "Át (Ace)",
    "rankNum": 1,
    "rankShort": "A",
    "suit": "Tép (Chuồn)",
    "suitCode": "clubs",
    "symbol": "♣",
    "color": "Màu đen",
    "colorType": "black",
    "image": "Porker/ace_of_clubs.png",
    "symbolCode": "o",
    "meaning": "Thầy Tà ở ngoài",
    "description": "Quân Át (Ace) (♣) mang ý nghĩa: Thầy Tà ở ngoài.",
    "advice": "Cảnh báo đối tượng tà sư từ bên ngoài đang tìm cách xâm nhập hoặc lôi kéo."
  },
  {
    "id": 28,
    "code": "2_clubs",
    "name": "Hai (2) Tép (Chuồn) ♣",
    "shortName": "2♣",
    "rank": "Hai (2)",
    "rankNum": 2,
    "rankShort": "2",
    "suit": "Tép (Chuồn)",
    "suitCode": "clubs",
    "symbol": "♣",
    "color": "Màu đen",
    "colorType": "black",
    "image": "Porker/2_of_clubs.png",
    "symbolCode": "p",
    "meaning": "Vong trẻ em ở ngoài / Con âm",
    "description": "Quân Hai (2) (♣) mang ý nghĩa: Vong trẻ em ở ngoài / Con âm.",
    "advice": "Vong nhi từ bên ngoài hoặc con âm theo quấy rầy, cần cầu siêu hóa giải."
  },
  {
    "id": 29,
    "code": "3_clubs",
    "name": "Ba (3) Tép (Chuồn) ♣",
    "shortName": "3♣",
    "rank": "Ba (3)",
    "rankNum": 3,
    "rankShort": "3",
    "suit": "Tép (Chuồn)",
    "suitCode": "clubs",
    "symbol": "♣",
    "color": "Màu đen",
    "colorType": "black",
    "image": "Porker/3_of_clubs.png",
    "symbolCode": "q",
    "meaning": "Âm binh súc sinh. Mất mộ",
    "description": "Quân Ba (3) (♣) mang ý nghĩa: Âm binh súc sinh. Mất mộ.",
    "advice": "Cảnh báo mộ phần bị thất lạc, mất dấu hoặc âm binh súc sinh bên ngoài xâm phạm."
  },
  {
    "id": 30,
    "code": "4_clubs",
    "name": "Bốn (4) Tép (Chuồn) ♣",
    "shortName": "4♣",
    "rank": "Bốn (4)",
    "rankNum": 4,
    "rankShort": "4",
    "suit": "Tép (Chuồn)",
    "suitCode": "clubs",
    "symbol": "♣",
    "color": "Màu đen",
    "colorType": "black",
    "image": "Porker/4_of_clubs.png",
    "symbolCode": "r",
    "meaning": "Âm binh người ở ngoài",
    "description": "Quân Bốn (4) (♣) mang ý nghĩa: Âm binh người ở ngoài.",
    "advice": "Âm binh ngoại giới nương theo tà niệm hoặc duyên xấu tìm tới."
  },
  {
    "id": 31,
    "code": "5_clubs",
    "name": "Năm (5) Tép (Chuồn) ♣",
    "shortName": "5♣",
    "rank": "Năm (5)",
    "rankNum": 5,
    "rankShort": "5",
    "suit": "Tép (Chuồn)",
    "suitCode": "clubs",
    "symbol": "♣",
    "color": "Màu đen",
    "colorType": "black",
    "image": "Porker/5_of_clubs.png",
    "symbolCode": "s",
    "meaning": "Bùa tàu",
    "description": "Quân Năm (5) (♣) mang ý nghĩa: Bùa tàu.",
    "advice": "Dấu hiệu của các loại bùa ngải ngoại bang (bùa Tàu) hoặc tà pháp cực mạnh."
  },
  {
    "id": 32,
    "code": "6_clubs",
    "name": "Sáu (6) Tép (Chuồn) ♣",
    "shortName": "6♣",
    "rank": "Sáu (6)",
    "rankNum": 6,
    "rankShort": "6",
    "suit": "Tép (Chuồn)",
    "suitCode": "clubs",
    "symbol": "♣",
    "color": "Màu đen",
    "colorType": "black",
    "image": "Porker/6_of_clubs.png",
    "symbolCode": "t",
    "meaning": "Nghiệp tâm linh bên ngoài",
    "description": "Quân Sáu (6) (♣) mang ý nghĩa: Nghiệp tâm linh bên ngoài.",
    "advice": "Các khoản nợ nghiệp tâm linh từ hoàn cảnh bên ngoài tác động dồn dập."
  },
  {
    "id": 33,
    "code": "7_clubs",
    "name": "Bảy (7) Tép (Chuồn) ♣",
    "shortName": "7♣",
    "rank": "Bảy (7)",
    "rankNum": 7,
    "rankShort": "7",
    "suit": "Tép (Chuồn)",
    "suitCode": "clubs",
    "symbol": "♣",
    "color": "Màu đen",
    "colorType": "black",
    "image": "Porker/7_of_clubs.png",
    "symbolCode": "u",
    "meaning": "Vong Nữ ở ngoài",
    "description": "Quân Bảy (7) (♣) mang ý nghĩa: Vong Nữ ở ngoài.",
    "advice": "Linh hồn nữ giới ngoài đường sá, đất khách vương vấn cần nương nhờ ánh sáng."
  },
  {
    "id": 34,
    "code": "8_clubs",
    "name": "Tám (8) Tép (Chuồn) ♣",
    "shortName": "8♣",
    "rank": "Tám (8)",
    "rankNum": 8,
    "rankShort": "8",
    "suit": "Tép (Chuồn)",
    "suitCode": "clubs",
    "symbol": "♣",
    "color": "Màu đen",
    "colorType": "black",
    "image": "Porker/8_of_clubs.png",
    "symbolCode": "v",
    "meaning": "Vong Nam ở ngoài",
    "description": "Quân Tám (8) (♣) mang ý nghĩa: Vong Nam ở ngoài.",
    "advice": "Linh hồn nam giới ngoại lai chưa siêu thoát tìm kiếm sự cứu giúp."
  },
  {
    "id": 35,
    "code": "9_clubs",
    "name": "Chín (9) Tép (Chuồn) ♣",
    "shortName": "9♣",
    "rank": "Chín (9)",
    "rankNum": 9,
    "rankShort": "9",
    "suit": "Tép (Chuồn)",
    "suitCode": "clubs",
    "symbol": "♣",
    "color": "Màu đen",
    "colorType": "black",
    "image": "Porker/9_of_clubs.png",
    "symbolCode": "w",
    "meaning": "Nghiệp ở đất khác",
    "description": "Quân Chín (9) (♣) mang ý nghĩa: Nghiệp ở đất khác.",
    "advice": "Nghiệp chướng liên quan đến nơi ở cũ hoặc vùng đất nơi phương xa."
  },
  {
    "id": 36,
    "code": "10_clubs",
    "name": "Mười (10) Tép (Chuồn) ♣",
    "shortName": "10♣",
    "rank": "Mười (10)",
    "rankNum": 10,
    "rankShort": "10",
    "suit": "Tép (Chuồn)",
    "suitCode": "clubs",
    "symbol": "♣",
    "color": "Màu đen",
    "colorType": "black",
    "image": "Porker/10_of_clubs.png",
    "symbolCode": "x",
    "meaning": "Thổ địa giả / Thổ địa nữ",
    "description": "Quân Mười (10) (♣) mang ý nghĩa: Thổ địa giả / Thổ địa nữ.",
    "advice": "Khí trường giả danh chánh thần, quỷ thần chiếm giữ bàn thờ đất đai."
  },
  {
    "id": 37,
    "code": "jack_clubs",
    "name": "J (Jack / Bồi) Tép (Chuồn) ♣",
    "shortName": "J♣",
    "rank": "J (Jack / Bồi)",
    "rankNum": 11,
    "rankShort": "J",
    "suit": "Tép (Chuồn)",
    "suitCode": "clubs",
    "symbol": "♣",
    "color": "Màu đen",
    "colorType": "black",
    "image": "Porker/jack_of_clubs.png",
    "symbolCode": "y",
    "meaning": "Quỷ / Yêu nữ",
    "description": "Quân J (Jack / Bồi) (♣) mang ý nghĩa: Quỷ / Yêu nữ.",
    "advice": "Thực thể quỷ quái nữ gây mê muội ái tình, xáo trộn tâm lý gia can."
  },
  {
    "id": 38,
    "code": "queen_clubs",
    "name": "Q (Queen / Đầm) Tép (Chuồn) ♣",
    "shortName": "Q♣",
    "rank": "Q (Queen / Đầm)",
    "rankNum": 12,
    "rankShort": "Q",
    "suit": "Tép (Chuồn)",
    "suitCode": "clubs",
    "symbol": "♣",
    "color": "Màu đen",
    "colorType": "black",
    "image": "Porker/queen_of_clubs.png",
    "symbolCode": "z",
    "meaning": "Quỷ / Yêu nam",
    "description": "Quân Q (Queen / Đầm) (♣) mang ý nghĩa: Quỷ / Yêu nam.",
    "advice": "Thực thể quỷ nam hung hãn gây tranh chấp, bạo lực hoặc tổn hao nguyên khí."
  },
  {
    "id": 39,
    "code": "king_clubs",
    "name": "K (King / Già) Tép (Chuồn) ♣",
    "shortName": "K♣",
    "rank": "K (King / Già)",
    "rankNum": 13,
    "rankShort": "K",
    "suit": "Tép (Chuồn)",
    "suitCode": "clubs",
    "symbol": "♣",
    "color": "Màu đen",
    "colorType": "black",
    "image": "Porker/king_of_clubs.png",
    "symbolCode": "n",
    "meaning": "Quỷ thần cõi âm",
    "description": "Quân K (King / Già) (♣) mang ý nghĩa: Quỷ thần cõi âm.",
    "advice": "Các thế lực quỷ thần cõi âm ngoại giới uy hiếp trường khí."
  },
  {
    "id": 40,
    "code": "ace_diamonds",
    "name": "Át (Ace) Rô ♦",
    "shortName": "A♦",
    "rank": "Át (Ace)",
    "rankNum": 1,
    "rankShort": "A",
    "suit": "Rô",
    "suitCode": "diamonds",
    "symbol": "♦",
    "color": "Màu đỏ",
    "colorType": "red",
    "image": "Porker/ace_of_diamonds.png",
    "symbolCode": "O",
    "meaning": "Thầy chánh pháp phương xa",
    "description": "Quân Át (Ace) (♦) mang ý nghĩa: Thầy chánh pháp phương xa.",
    "advice": "Minh sư hoặc thiện tri thức từ phương xa mang chánh đạo tới hỗ trợ."
  },
  {
    "id": 41,
    "code": "2_diamonds",
    "name": "Hai (2) Rô ♦",
    "shortName": "2♦",
    "rank": "Hai (2)",
    "rankNum": 2,
    "rankShort": "2",
    "suit": "Rô",
    "suitCode": "diamonds",
    "symbol": "♦",
    "color": "Màu đỏ",
    "colorType": "red",
    "image": "Porker/2_of_diamonds.png",
    "symbolCode": "P",
    "meaning": "Vong trẻ em Nam trợ duyên",
    "description": "Quân Hai (2) (♦) mang ý nghĩa: Vong trẻ em Nam trợ duyên.",
    "advice": "Linh hồn trẻ thơ mang năng lượng trong sáng báo hiệu tin vui."
  },
  {
    "id": 42,
    "code": "3_diamonds",
    "name": "Ba (3) Rô ♦",
    "shortName": "3♦",
    "rank": "Ba (3)",
    "rankNum": 3,
    "rankShort": "3",
    "suit": "Rô",
    "suitCode": "diamonds",
    "symbol": "♦",
    "color": "Màu đỏ",
    "colorType": "red",
    "image": "Porker/3_of_diamonds.png",
    "symbolCode": "Q",
    "meaning": "Rồng xuất hiện. Mộ tốt",
    "description": "Quân Ba (3) (♦) mang ý nghĩa: Rồng xuất hiện. Mộ tốt.",
    "advice": "Long mạch hiển lộ, mồ mả vượng phát khí lành sinh tài phát lộc."
  },
  {
    "id": 43,
    "code": "4_diamonds",
    "name": "Bốn (4) Rô ♦",
    "shortName": "4♦",
    "rank": "Bốn (4)",
    "rankNum": 4,
    "rankShort": "4",
    "suit": "Rô",
    "suitCode": "diamonds",
    "symbol": "♦",
    "color": "Màu đỏ",
    "colorType": "red",
    "image": "Porker/4_of_diamonds.png",
    "symbolCode": "R",
    "meaning": "Con cháu hiếu thảo",
    "description": "Quân Bốn (4) (♦) mang ý nghĩa: Con cháu hiếu thảo.",
    "advice": "Đạo hiếu rạng ngời, phước ấm tổ tiên gia hộ thế hệ sau hiển đạt."
  },
  {
    "id": 44,
    "code": "5_diamonds",
    "name": "Năm (5) Rô ♦",
    "shortName": "5♦",
    "rank": "Năm (5)",
    "rankNum": 5,
    "rankShort": "5",
    "suit": "Rô",
    "suitCode": "diamonds",
    "symbol": "♦",
    "color": "Màu đỏ",
    "colorType": "red",
    "image": "Porker/5_of_diamonds.png",
    "symbolCode": "S",
    "meaning": "Bùa đã được giải / Ứng lệnh",
    "description": "Quân Năm (5) (♦) mang ý nghĩa: Bùa đã được giải / Ứng lệnh.",
    "advice": "Lệnh giải trừ bùa ngải đã ban xuống, mọi ràng buộc tà pháp tiêu biến."
  },
  {
    "id": 45,
    "code": "6_diamonds",
    "name": "Sáu (6) Rô ♦",
    "shortName": "6♦",
    "rank": "Sáu (6)",
    "rankNum": 6,
    "rankShort": "6",
    "suit": "Rô",
    "suitCode": "diamonds",
    "symbol": "♦",
    "color": "Màu đỏ",
    "colorType": "red",
    "image": "Porker/6_of_diamonds.png",
    "symbolCode": "T",
    "meaning": "Nghiệp lành",
    "description": "Quân Sáu (6) (♦) mang ý nghĩa: Nghiệp lành.",
    "advice": "Thiện duyên kết quả ngọt ngào, công đức tích lũy bắt đầu khai hoa."
  },
  {
    "id": 46,
    "code": "7_diamonds",
    "name": "Bảy (7) Rô ♦",
    "shortName": "7♦",
    "rank": "Bảy (7)",
    "rankNum": 7,
    "rankShort": "7",
    "suit": "Rô",
    "suitCode": "diamonds",
    "symbol": "♦",
    "color": "Màu đỏ",
    "colorType": "red",
    "image": "Porker/7_of_diamonds.png",
    "symbolCode": "U",
    "meaning": "Uyển / Thiên nữ",
    "description": "Quân Bảy (7) (♦) mang ý nghĩa: Uyển / Thiên nữ.",
    "advice": "Chư vị Thiên Nữ giáng lâm mang lại sự thanh cao, an lành và trí tuệ mẫn tiệp."
  },
  {
    "id": 47,
    "code": "8_diamonds",
    "name": "Tám (8) Rô ♦",
    "shortName": "8♦",
    "rank": "Tám (8)",
    "rankNum": 8,
    "rankShort": "8",
    "suit": "Rô",
    "suitCode": "diamonds",
    "symbol": "♦",
    "color": "Màu đỏ",
    "colorType": "red",
    "image": "Porker/8_of_diamonds.png",
    "symbolCode": "V",
    "meaning": "Thiên nam",
    "description": "Quân Tám (8) (♦) mang ý nghĩa: Thiên nam.",
    "advice": "Chư vị Thiên Nam dũng mãnh bảo vệ thân tâm, tiếp thêm dũng khí."
  },
  {
    "id": 48,
    "code": "9_diamonds",
    "name": "Chín (9) Rô ♦",
    "shortName": "9♦",
    "rank": "Chín (9)",
    "rankNum": 9,
    "rankShort": "9",
    "suit": "Rô",
    "suitCode": "diamonds",
    "symbol": "♦",
    "color": "Màu đỏ",
    "colorType": "red",
    "image": "Porker/9_of_diamonds.png",
    "symbolCode": "W",
    "meaning": "Thông tin về phủ",
    "description": "Quân Chín (9) (♦) mang ý nghĩa: Thông tin về phủ.",
    "advice": "Chỉ dẫn tâm linh rõ ràng liên quan đến cửa Phủ, nghi lễ trang nghiêm."
  },
  {
    "id": 49,
    "code": "10_diamonds",
    "name": "Mười (10) Rô ♦",
    "shortName": "10♦",
    "rank": "Mười (10)",
    "rankNum": 10,
    "rankShort": "10",
    "suit": "Rô",
    "suitCode": "diamonds",
    "symbol": "♦",
    "color": "Màu đỏ",
    "colorType": "red",
    "image": "Porker/10_of_diamonds.png",
    "symbolCode": "X",
    "meaning": "Thần thú",
    "description": "Quân Mười (10) (♦) mang ý nghĩa: Thần thú.",
    "advice": "Linh thú cõi giới hộ trì, uy lực xua đuổi ám khí bảo vệ gia trạch."
  },
  {
    "id": 50,
    "code": "jack_diamonds",
    "name": "J (Jack / Bồi) Rô ♦",
    "shortName": "J♦",
    "rank": "J (Jack / Bồi)",
    "rankNum": 11,
    "rankShort": "J",
    "suit": "Rô",
    "suitCode": "diamonds",
    "symbol": "♦",
    "color": "Màu đỏ",
    "colorType": "red",
    "image": "Porker/jack_of_diamonds.png",
    "symbolCode": "Y",
    "meaning": "Hộ pháp cứu độ",
    "description": "Quân J (Jack / Bồi) (♦) mang ý nghĩa: Hộ pháp cứu độ.",
    "advice": "Chư vị Hộ Pháp ra tay tiếp cứu kịp thời trong cơn hoạn nạn."
  },
  {
    "id": 51,
    "code": "queen_diamonds",
    "name": "Q (Queen / Đầm) Rô ♦",
    "shortName": "Q♦",
    "rank": "Q (Queen / Đầm)",
    "rankNum": 12,
    "rankShort": "Q",
    "suit": "Rô",
    "suitCode": "diamonds",
    "symbol": "♦",
    "color": "Màu đỏ",
    "colorType": "red",
    "image": "Porker/queen_of_diamonds.png",
    "symbolCode": "Z",
    "meaning": "Các vị tiên thánh cõi cao",
    "description": "Quân Q (Queen / Đầm) (♦) mang ý nghĩa: Các vị tiên thánh cõi cao.",
    "advice": "Tiên Thánh thượng giới soi đường chỉ lối, mở mang trí huệ sáng suốt."
  },
  {
    "id": 52,
    "code": "king_diamonds",
    "name": "K (King / Già) Rô ♦",
    "shortName": "K♦",
    "rank": "K (King / Già)",
    "rankNum": 13,
    "rankShort": "K",
    "suit": "Rô",
    "suitCode": "diamonds",
    "symbol": "♦",
    "color": "Màu đỏ",
    "colorType": "red",
    "image": "Porker/king_of_diamonds.png",
    "symbolCode": "N",
    "meaning": "Các vị tiên thánh cõi cao tối thượng",
    "description": "Quân K (King / Già) (♦) mang ý nghĩa: Các vị tiên thánh cõi cao tối thượng.",
    "advice": "Oai lực của chư Thần Tiên cõi tối cao ban phước lành vô lượng."
  }
];

const POKER_COMBOS_DATA = [
  {
    "id": "combo_2_6_3",
    "ranks": [
      2,
      6,
      3
    ],
    "color": "any",
    "suit": "any",
    "name": "Bộ 2 - 6 - 3",
    "meaning": "Lắng nghe thông tin từ các vị",
    "description": "Bạn đang nhận được thông điệp từ chư vị vô hình; hãy giữ tâm định tĩnh để lắng nghe sự chỉ dẫn."
  },
  {
    "id": "combo_5_7_8_black",
    "ranks": [
      5,
      7,
      8
    ],
    "color": "black",
    "suit": "any",
    "name": "Bộ 5 - 7 - 8 Đen",
    "meaning": "Nghiệp nặng",
    "description": "Cảnh báo có khối nghiệp báo sâu dày đang hiện diện; cần chí thành sám hối, phóng sinh và tu tập tích đức."
  },
  {
    "id": "combo_5_7_8_red",
    "ranks": [
      5,
      7,
      8
    ],
    "color": "red",
    "suit": "any",
    "name": "Bộ 5 - 7 - 8 Đỏ",
    "meaning": "Xác nhận từ các vị Hộ Pháp",
    "description": "Điềm lành: Chư vị Hộ Pháp đã chứng giám và ban lệnh bảo hộ vững chắc cho bạn."
  },
  {
    "id": "combo_4_6_3",
    "ranks": [
      4,
      6,
      3
    ],
    "color": "any",
    "suit": "any",
    "name": "Bộ 4 - 6 - 3",
    "meaning": "Vong muốn nói chuyện",
    "description": "Có chân linh hoặc vong linh có duyên muốn giao tiếp, gửi gắm lời nhắn hoặc xin sự trợ giúp hồi hướng."
  },
  {
    "id": "combo_2_7_9",
    "ranks": [
      2,
      7,
      9
    ],
    "color": "any",
    "suit": "any",
    "name": "Bộ 2 - 7 - 9",
    "meaning": "Quỷ nam",
    "description": "Báo hiệu sự hiện diện của quỷ nam hung hãn; cần cẩn trọng tránh xung đột, nóng giận và giữ giới đức."
  },
  {
    "id": "combo_2_6_9",
    "ranks": [
      2,
      6,
      9
    ],
    "color": "any",
    "suit": "any",
    "name": "Bộ 2 - 6 - 9",
    "meaning": "Quỷ nữ",
    "description": "Báo hiệu năng lượng xáo trộn của quỷ nữ; cần thanh lọc tâm ý, tránh bi lụy cảm xúc tiêu cực."
  },
  {
    "id": "combo_6_7_9",
    "ranks": [
      6,
      7,
      9
    ],
    "color": "any",
    "suit": "any",
    "name": "Bộ 6 - 7 - 9",
    "meaning": "Thiếu thông tin",
    "description": "Hiện tại chưa đủ cơ duyên hoặc thiếu dữ liệu tâm linh; chưa nên vội vàng kết luận hay hành động."
  },
  {
    "id": "combo_7_6_3",
    "ranks": [
      7,
      6,
      3
    ],
    "color": "any",
    "suit": "any",
    "name": "Bộ 7 - 6 - 3",
    "meaning": "Vong muốn tấn công",
    "description": "Cảnh báo nguy cơ bị vong linh oán hận công kích hoặc quấy quả; cần gia tăng trì chú và an vị hộ thân."
  },
  {
    "id": "combo_5_6_8_ro",
    "ranks": [
      5,
      6,
      8
    ],
    "color": "any",
    "suit": "diamonds",
    "name": "Bộ 5 - 6 - 8 Rô ♦",
    "meaning": "Xác nhận / Chỉ dẫn từ Bồ Tát",
    "description": "Điềm đại cát tường: Đức Quán Thế Âm Bồ Tát soi tỏ và xác nhận hướng đi của bạn là hoàn toàn đúng đắn."
  },
  {
    "id": "combo_5_6_8",
    "ranks": [
      5,
      6,
      8
    ],
    "color": "any",
    "suit": "any",
    "name": "Bộ 5 - 6 - 8",
    "meaning": "Tác ý và tri giác đang đúng / Xác nhận",
    "description": "Tác ý, suy nghĩ và cảm nhận hiện tại của bạn đang chuẩn xác với chân lý; hãy tự tin tiến bước."
  },
  {
    "id": "combo_4_8_9",
    "ranks": [
      4,
      8,
      9
    ],
    "color": "any",
    "suit": "any",
    "name": "Bộ 4 - 8 - 9",
    "meaning": "Thực thể linh hồn ký sinh trong cơ thể",
    "description": "Báo hiệu có một thực thể bất kỳ nào đó dạng linh hồn (súc sinh - ấu trùng) có ý thức, bản ngã đang ký sinh trong cơ thể và điều khiển hoặc nương nhờ năng lượng con người."
  },
  {
    "id": "combo_5_7_9",
    "ranks": [
      5,
      7,
      9
    ],
    "color": "any",
    "suit": "any",
    "name": "Bộ 5 - 7 - 9",
    "meaning": "Âm binh và vong ký sinh trong người",
    "description": "Âm binh và vong linh nói chung (không phân biệt nam nữ) đang ký sinh ở trong người; cần thanh tẩy năng lượng khẩn cấp."
  },
  {
    "id": "combo_5_6_3",
    "ranks": [
      5,
      6,
      3
    ],
    "color": "any",
    "suit": "any",
    "name": "Bộ 5 - 6 - 3",
    "meaning": "Nợ nghiệp",
    "description": "Dấu hiệu các khoản nợ tiền kiếp đang đến kỳ đòi lại; hãy hoan hỷ sám hối và trả nghiệp với lòng từ bi."
  },
  {
    "id": "combo_4_9_5",
    "ranks": [
      4,
      9,
      5
    ],
    "color": "any",
    "suit": "any",
    "name": "Bộ 4 - 9 - 5",
    "meaning": "Gia tiên báo việc âm khẩn cấp",
    "description": "Gia tiên báo việc âm (thông thường là đang bị âm binh, yêu quỷ quấy phá, hoặc đang hoảng sợ cần con cháu cứu giúp)."
  },
  {
    "id": "combo_2_9_4",
    "ranks": [
      2,
      9,
      4
    ],
    "color": "any",
    "suit": "any",
    "name": "Bộ 2 - 9 - 4",
    "meaning": "Thông tin giả",
    "description": "Cảnh báo thông tin bạn vừa nhận được hoặc đang nghĩ là thông tin sai lạc, giả tướng hoặc bị nhiễu loạn."
  },
  {
    "id": "combo_3_6_9",
    "ranks": [
      3,
      6,
      9
    ],
    "color": "any",
    "suit": "any",
    "name": "Bộ 3 - 6 - 9",
    "meaning": "Gia hộ / Thông pháp / Nhắc nhở tinh tấn",
    "description": "Bạn đang nhận được sự gia hộ và thông pháp; tuy nhiên có lời nhắc nhở cần tập trung hơn, tránh tà kiến xao lãng."
  }
];
